# Server deployment profile for Kubernetes service discovery and Envoy Gateway ingress.
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.cloud.discovery.client.simple.instances.payment-service[0].uri=http://payment-service:9114
spring.datasource.url=${PAYMENT_ORCHESTRATOR_SERVICE_DATASOURCE_URL:jdbc:postgresql://postgres:5432/payment_orchestrator_service}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${PAYMENT_ORCHESTRATOR_SERVICE_DATASOURCE_USERNAME:${SPRING_DATASOURCE_USERNAME:postgres}}
spring.datasource.password=${PAYMENT_ORCHESTRATOR_SERVICE_DATASOURCE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:postgres}}
spring.mongodb.uri=${PAYMENT_ORCHESTRATOR_SERVICE_MONGODB_URI:mongodb://mongo:27017/payment_orchestrator_service}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_URI:http://sso-auth-service:9001/.well-known/jwks.json}
service.internal.username=${PAYMENT_ORCHESTRATOR_SERVICE_INTERNAL_USERNAME:payment_orchestrator_internal}
service.internal.password=${PAYMENT_ORCHESTRATOR_SERVICE_INTERNAL_PASSWORD:payment_orchestrator_secret}
