server.port=9002
spring.application.name=sso-user-service
eureka.client.serviceUrl.defaultZone=http://admin:CyanAdmin@localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}
spring.datasource.url=jdbc:h2:file:./data/sso-user-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/.well-known/jwks.json
