create table if not exists dynamic_entity_definitions (
    id bigint generated by default as identity primary key,
    service_key varchar(255),
    tenant_key varchar(255),
    site_key varchar(255),
    entity_key varchar(255),
    entity_type varchar(255),
    title varchar(255),
    definition_json text,
    active boolean not null default true,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    revision bigint not null default 0,
    constraint uk_dynamic_entity_definition_scope
        unique (service_key, tenant_key, site_key, entity_key)
);
