pluginManagement {
    repositories {
        maven { url 'https://mirror-maven.runflare.com/gradle-plugins/' }
        maven { url 'https://mirror-maven.runflare.com/maven2/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        maven { url 'https://mirror-maven.runflare.com/maven2/' }
        maven { url 'https://mirror-maven.runflare.com/android/maven2/' }
        maven { url 'https://mirror-maven.runflare.com/gradle-plugins/' }
        mavenCentral()
    }
}

rootProject.name = 'root'
include 'tax-pay-sys'
include 'discovery-server'
include 'api-gateway'
include 'factor-service'
include 'buyer-service'
include 'client-service'
include 'product-service'
include 'generic'
include 'dynamic-entity-core'
include 'sso-common'
include 'sso-auth-service'
include 'sso-user-service'
include 'sso-captcha-service'
include 'sso-otp-service'
include 'sso-session-service'
include 'sso-fido-service'
include 'content-service'
include 'catalog-service'
include 'crm-service'
include 'commerce-service'
include 'finance-service'
include 'inventory-service'
include 'report-service'
include 'processor-service'
include 'event-service'
include 'crm-automation-service'
include 'finance-automation-service'
include 'inventory-automation-service'
include 'report-automation-service'
