server.port=${BATCH_WORKER_SERVICE_PORT:9127}
spring.datasource.url=${BATCH_WORKER_DATASOURCE_URL}
spring.datasource.username=${BATCH_WORKER_DATASOURCE_USERNAME}
spring.datasource.password=${BATCH_WORKER_DATASOURCE_PASSWORD}
spring.batch.jdbc.initialize-schema=${BATCH_WORKER_INITIALIZE_SCHEMA:never}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SSO_JWK_SET_URI:http://sso-auth-service:9001/.well-known/jwks.json}
eureka.client.serviceUrl.defaultZone=${EUREKA_DEFAULT_ZONE:http://admin:CyanAdmin@discovery-server:8761/eureka}
service.internal.username=${BATCH_WORKER_SERVICE_INTERNAL_USERNAME:batch_worker_internal}
service.internal.password=${BATCH_WORKER_SERVICE_INTERNAL_PASSWORD:batch_worker_secret}
