server.port=9110
spring.application.name=crm-automation-service
eureka.client.serviceUrl.defaultZone=http://admin:CyanAdmin@localhost:8761/eureka
spring.datasource.url=${CRM_AUTOMATION_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crm_automation_service}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${CRM_AUTOMATION_SERVICE_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${CRM_AUTOMATION_SERVICE_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=crm-automation-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
business.events.topic=business-events
