"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Background, BaseEdge, Controls, Handle, MarkerType, MiniMap, Position, ReactFlow, addEdge, applyEdgeChanges, applyNodeChanges, getBezierPath, type Connection, type Edge, type EdgeChange, type EdgeProps, type Node, type NodeChange, type NodeProps } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { useRouter } from "next/navigation";
import { AsyncButton, CodeViewer, ConfirmDialog, EmptyState, Select, StatusBadge } from "@/components/ui/primitives";
import { useToast } from "@/components/ui/toast-provider";
import { usePanel } from "@/components/panel-provider";
import { useScopeAccess } from "@/components/scope-access-provider";
import { analyzeN8n, automationLifecycle, exportN8n, importN8n, listAutomationNodeMetadata, listCredentials, saveAutomationFlow, startManualExecution, type AutomationFlow, type AutomationNodeMetadata, type CredentialReference } from "@/lib/automation-api";

const labels:Record<string,{en:string;fa:string}>={AI_OPERATION:{en:"AI operation",fa:"عملیات هوش مصنوعی"},MANUAL_TRIGGER:{en:"Manual trigger",fa:"شروع دستی"},SCHEDULE_TRIGGER:{en:"Schedule",fa:"زمان‌بندی"},CALL_API:{en:"Call API",fa:"فراخوانی API"},IF:{en:"Condition",fa:"شرط"},MAP_FIELDS:{en:"Map fields",fa:"نگاشت فیلدها"},END:{en:"End",fa:"پایان"}};
const categories=(type:string)=>type.includes("TRIGGER")?"Triggers":type==="AI_OPERATION"?"AI":type.includes("CALL")||type.includes("HTTP")?"Integrations":type==="IF"||type==="SWITCH"?"Logic":"Data & flow";
const blank=(flowKey="") : AutomationFlow=>({flowKey,version:1,name:"",active:false,entryNodeId:"",runtimeMode:"VARIABLES",nodes:[],edges:[],inputsSchema:{},outputsSchema:{},labels:[],environment:"default",lifecycleStatus:"DRAFT",requiredRoles:[],settings:{},pinData:{}});
const nodeFrom=(type:string,index:number)=>({id:`${type.toLowerCase()}-${crypto.randomUUID().slice(0,8)}`,type,name:labels[type]?.en??type.replaceAll("_"," ").toLowerCase(),enabled:true,config:type==="AI_OPERATION"?{operation:"TRANSFORM_DATA",instructions:"",input:"${variables}",resultPath:"aiResult"}:{},position:{x:120+(index%3)*220,y:100+Math.floor(index/3)*130},data:{}});
const nodeIcon=(type:string)=>type==="AI_OPERATION"?"✦":type.includes("TRIGGER")?"▶":type==="IF"||type==="SWITCH"?"◇":type.includes("API")||type.includes("HTTP")?"↗":type==="END"?"■":"◆";
const nodeTone=(type:string)=>type==="AI_OPERATION"?"ai":type.includes("TRIGGER")?"trigger":type==="IF"||type==="SWITCH"?"logic":type==="END"?"end":"action";
function AutomationNodeCard({data,selected}:NodeProps){const value=data as {label?:string;status?:string;type?:string};const type=String(value.type??"");return <div className={`automation-node-card ${nodeTone(type)} ${selected?"selected":""} ${value.status==="disabled"?"disabled":""}`}>
  <div className="automation-node-tile">
    <Handle type="target" position={Position.Left} isConnectable/>
    <span className="automation-node-icon" aria-hidden>{nodeIcon(type)}</span>
    <span className="automation-node-state" aria-label={value.status==="disabled"?"Disabled":"Enabled"}/>
    <Handle type="source" position={Position.Right} isConnectable/>
  </div>
  <div className="automation-node-label"><strong>{String(value.label??type)}</strong><small>{type.replaceAll("_"," ").toLowerCase()}</small></div>
</div>}
function AutomationEdge(props:EdgeProps){const [path]=getBezierPath(props);return <BaseEdge path={path} markerEnd={props.markerEnd} style={props.style}/>}
const automationNodeTypes={automationCard:AutomationNodeCard};
const automationNodeHandles=[{id:null,type:"target" as const,position:Position.Left,x:9,y:25,width:14,height:14},{id:null,type:"source" as const,position:Position.Right,x:89,y:25,width:14,height:14}];
const automationEdgeTypes={automationEdge:AutomationEdge};

export function AutomationBuilder({initial,returnTo}: {initial?:AutomationFlow;returnTo?:string}){
 const {locale}=usePanel();const {tenantKey,siteKey,can}=useScopeAccess();const scope=useMemo(()=>({tenantKey:tenantKey??undefined,siteKey:siteKey??undefined}),[tenantKey,siteKey]);const canManage=can("automation.manage");const canExecute=can("automation.execute");const {showToast}=useToast();const router=useRouter();const [flow,setFlow]=useState<AutomationFlow>(initial??blank());const [metadata,setMetadata]=useState<AutomationNodeMetadata[]>([]);const [credentials,setCredentials]=useState<CredentialReference[]>([]);const [selected,setSelected]=useState<string|null>(null);const [query,setQuery]=useState("");const [pending,setPending]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [runInput,setRunInput]=useState("{}");const [runInputError,setRunInputError]=useState<string|null>(null);const [testOpen,setTestOpen]=useState(false);const [confirmAction,setConfirmAction]=useState<"activate"|"delete-node"|null>(null);const [dirty,setDirty]=useState(!initial);const initialRef=useRef(initial);
 const [n8nWorkflow,setN8nWorkflow]=useState<unknown|null>(null);const [n8nAnalysis,setN8nAnalysis]=useState<Record<string,unknown>|null>(null);
 useEffect(()=>{if(!tenantKey)return;Promise.all([listAutomationNodeMetadata(),canManage?listCredentials(scope):Promise.resolve([])]).then(([m,c])=>{setMetadata(m);setCredentials(c)}).catch(e=>setError(e instanceof Error?e.message:String(e)))},[canManage,scope,tenantKey]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard)},[dirty]);
 const nodes=useMemo<Node[]>(()=>flow.nodes.map(n=>({id:n.id,type:"automationCard",position:{x:Number(n.position?.x??0),y:Number(n.position?.y??0)},width:112,height:112,handles:automationNodeHandles,data:{label:n.name,status:n.enabled?"":"disabled",type:n.type},selected:n.id===selected})),[flow.nodes,selected]);
 const edges=useMemo<Edge[]>(()=>flow.edges.map(e=>({id:e.id,type:"automationEdge",source:e.fromNodeId,target:e.toNodeId,sourceHandle:e.fromPort??undefined,targetHandle:e.toPort??undefined,animated:flow.active,markerEnd:{type:MarkerType.ArrowClosed},className:"automation-edge"})),[flow.edges,flow.active]);
 const selectedNode=flow.nodes.find(n=>n.id===selected);
 const updateNode=(patch:Record<string,unknown>)=>{setFlow(v=>({...v,nodes:v.nodes.map(n=>n.id===selected?{...n,...patch}:n)}));setDirty(true)};
 const onNodesChange=useCallback((changes:NodeChange[])=>{const next=applyNodeChanges(changes,nodes);setFlow(v=>({...v,nodes:v.nodes.map(n=>{const x=next.find(item=>item.id===n.id);return x?{...n,position:x.position}:n})}));if(changes.some(c=>c.type==="position"||c.type==="remove"))setDirty(true)},[nodes]);
 const onEdgesChange=useCallback((changes:EdgeChange[])=>{const next=applyEdgeChanges(changes,edges);setFlow(v=>({...v,edges:next.map(e=>({id:e.id,fromNodeId:e.source,fromPort:e.sourceHandle,toNodeId:e.target,toPort:e.targetHandle}))}));setDirty(true)},[edges]);
 const connect=useCallback((connection:Connection)=>{const next=addEdge({...connection,id:`edge-${crypto.randomUUID().slice(0,8)}`},edges);setFlow(v=>({...v,edges:next.map(e=>({id:e.id,fromNodeId:e.source,fromPort:e.sourceHandle,toNodeId:e.target,toPort:e.targetHandle}))}));setDirty(true)},[edges]);
 const addConnection=useCallback((fromNodeId:string,toNodeId:string)=>{if(!fromNodeId||!toNodeId||fromNodeId===toNodeId)return;setFlow(v=>v.edges.some(edge=>edge.fromNodeId===fromNodeId&&edge.toNodeId===toNodeId)?v:{...v,edges:[...v.edges,{id:`edge-${crypto.randomUUID().slice(0,8)}`,fromNodeId,toNodeId}]});setDirty(true)},[]);
 const add=(type:string)=>{if(!canManage)return;const node=nodeFrom(type,flow.nodes.length);setFlow(v=>({...v,nodes:[...v.nodes,node],entryNodeId:v.entryNodeId||node.id}));setSelected(node.id);setDirty(true)};
 const mutate=async(key:string,fn:()=>Promise<AutomationFlow>)=>{if(pending)return;setPending(key);setError(null);try{const saved=await fn();setFlow(saved);setDirty(false);showToast({tone:"success",title:key==="save"?(locale==="fa"?"اتوماسیون ذخیره شد":"Automation saved"):(locale==="fa"?"چرخه عمر به‌روزرسانی شد":"Lifecycle updated")});if(!initialRef.current){initialRef.current=saved;router.replace(returnTo??`/automations/${encodeURIComponent(saved.flowKey)}`)}}catch(e){const message=e instanceof Error?e.message:String(e);setError(message);showToast({tone:"error",title:locale==="fa"?"عملیات ناموفق بود":"Action failed",message})}finally{setPending(null)}};
 const save=()=>mutate("save",()=>saveAutomationFlow(flow,scope));
 const lifecycle=(action:"SUBMIT"|"APPROVE"|"ACTIVATE")=>mutate(action,()=>automationLifecycle(flow.flowKey,flow.version,action,scope));
 const test=async()=>{if(pending||!canExecute)return;let input:Record<string,unknown>;try{const parsed=JSON.parse(runInput);if(!parsed||Array.isArray(parsed)||typeof parsed!=="object")throw new Error();input=parsed}catch{setRunInputError(locale==="fa"?"ورودی باید یک شیء JSON معتبر باشد.":"Test input must be a valid JSON object.");return}setRunInputError(null);setPending("test");setError(null);try{if(dirty)await saveAutomationFlow(flow,scope);const run=await startManualExecution(flow.flowKey,input,scope);showToast({tone:"success",title:locale==="fa"?"اجرای آزمایشی شروع شد":"Test run started",message:run.executionId});router.push(`/automations/executions/${run.executionId}`)}catch(e){const message=e instanceof Error?e.message:String(e);setError(message);showToast({tone:"error",title:locale==="fa"?"اجرای آزمایشی ناموفق بود":"Test run failed",message})}finally{setPending(null)}};
 const analyzeFile=async(file?:File)=>{if(!file||pending||!canManage)return;setPending("analyze-n8n");setError(null);setN8nAnalysis(null);try{const workflow=JSON.parse(await file.text());const analysis=await analyzeN8n(workflow,scope);setN8nWorkflow(workflow);setN8nAnalysis(analysis)}catch(e){setN8nWorkflow(null);setError(e instanceof Error?e.message:String(e))}finally{setPending(null)}};
 const importAnalyzed=async()=>{if(!n8nWorkflow||n8nAnalysis?.compatible!==true||pending||!canManage)return;setPending("import-n8n");setError(null);try{const imported=await importN8n(n8nWorkflow,flow.flowKey||undefined,scope);setFlow(imported);setDirty(false);setN8nWorkflow(null);setN8nAnalysis(null);initialRef.current=imported;showToast({tone:"success",title:locale==="fa"?"گردش‌کار وارد شد":"Workflow imported"});router.replace(`/automations/${encodeURIComponent(imported.flowKey)}`)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setPending(null)}};
 const downloadExport=async()=>{if(!flow.flowKey||pending)return;setPending("export-n8n");setError(null);try{const payload=await exportN8n(flow.flowKey,flow.version,scope);const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`${flow.flowKey}-v${flow.version}.n8n.json`;link.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setPending(null)}};
 const available=metadata.filter(m=>(m.label??m.type).toLowerCase().includes(query.toLowerCase()));
 const grouped=available.reduce<Record<string,AutomationNodeMetadata[]>>((all,item)=>{(all[categories(item.type)]??=[]).push(item);return all},{});
 return <section className={`automation-workspace ${canManage ? "" : "read-only"}`}>
  {!canManage?<div className="operational-banner warning" role="status">{locale==="fa"?"دسترسی مشاهده دارید. برای تغییر فلو به مجوز automation.manage نیاز است.":"You have view access. Editing requires automation.manage."}</div>:null}
  <div className="page-action-bar automation-toolbar"><div><StatusBadge tone={flow.active?"success":"neutral"}>{flow.lifecycleStatus}</StatusBadge><span>v{flow.version}</span>{dirty?<small className="unsaved-indicator"><i/>{locale==="fa"?"ذخیره‌نشده":"Unsaved changes"}</small>:<small className="saved-indicator">✓ {locale==="fa"?"ذخیره شده":"Saved"}</small>}</div><div><label className="secondary-pill automation-import-action" aria-disabled={Boolean(pending)}>{pending==="analyze-n8n"?(locale==="fa"?"تحلیل…":"Analyzing…"):(locale==="fa"?"ورود n8n":"Import n8n")}<input type="file" accept="application/json,.json" hidden disabled={Boolean(pending)} onChange={e=>{analyzeFile(e.target.files?.[0]).catch(()=>null);e.currentTarget.value=""}}/></label>{initial?<AsyncButton className="secondary-pill automation-export-action" pending={pending==="export-n8n"} onClick={downloadExport}>{locale==="fa"?"خروجی n8n":"Export n8n"}</AsyncButton>:null}<button className="secondary-pill editor-mobile-toggle" onClick={()=>setSelected("__settings")}>{locale==="fa"?"تنظیمات":"Settings"}</button><button className="secondary-pill test-run-trigger" disabled={!flow.flowKey||!flow.nodes.length||Boolean(pending)} onClick={()=>setTestOpen(true)}>▶ {locale==="fa"?"اجرای آزمایشی":"Test run"}</button><AsyncButton pending={pending==="save"} pendingLabel={locale==="fa"?"ذخیره…":"Saving…"} disabled={!flow.flowKey||!flow.name||!flow.nodes.length} onClick={save}>{locale==="fa"?"ذخیره":"Save draft"}</AsyncButton>{flow.lifecycleStatus==="DRAFT"?<AsyncButton className="secondary-pill" pending={pending==="SUBMIT"} onClick={()=>lifecycle("SUBMIT")}>{locale==="fa"?"ارسال":"Submit"}</AsyncButton>:null}{flow.lifecycleStatus==="PENDING_APPROVAL"?<AsyncButton className="secondary-pill" pending={pending==="APPROVE"} onClick={()=>lifecycle("APPROVE")}>{locale==="fa"?"تأیید":"Approve"}</AsyncButton>:null}{flow.lifecycleStatus==="APPROVED"?<AsyncButton pending={pending==="ACTIVATE"} onClick={()=>setConfirmAction("activate")}>{locale==="fa"?"فعال‌سازی":"Activate"}</AsyncButton>:null}</div></div>
  {n8nAnalysis?<div className={`operational-banner ${n8nAnalysis.compatible===true?"success":"error"}`} role="status"><span>{n8nAnalysis.compatible===true?(locale==="fa"?"همه گره‌ها پشتیبانی می‌شوند؛ هیچ مقدار مخفی وارد نمی‌شود.":"All nodes are supported; credential secrets will not be imported."):(locale==="fa"?`ورود مسدود است: ${Array.isArray(n8nAnalysis.unsupportedNodes)?n8nAnalysis.unsupportedNodes.length:0} گره پشتیبانی‌نشده`:`Import blocked: ${Array.isArray(n8nAnalysis.unsupportedNodes)?n8nAnalysis.unsupportedNodes.length:0} unsupported nodes`)}</span>{n8nAnalysis.compatible===true?<AsyncButton pending={pending==="import-n8n"} onClick={importAnalyzed}>{locale==="fa"?"تأیید ورود":"Confirm import"}</AsyncButton>:null}<button aria-label="Dismiss n8n analysis" onClick={()=>{setN8nAnalysis(null);setN8nWorkflow(null)}}>×</button></div>:null}
  {error?<div className="operational-banner error" role="alert"><span>{error}</span><button onClick={()=>setError(null)}>×</button></div>:null}
  <div className="automation-editor-grid">
   <aside className="automation-palette"><header><strong>{locale==="fa"?"گره‌ها":"Node library"}</strong><input aria-label={locale==="fa"?"جستجوی گره":"Search nodes"} value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==="fa"?"جستجو…":"Search nodes…"}/></header>{metadata.length===0&&!error?<div className="palette-loading" aria-label="Loading nodes"><span/><span/><span/></div>:Object.entries(grouped).map(([category,items])=><section key={category}><h3>{category}</h3>{items.map(item=><button key={item.type} onClick={()=>add(item.type)}><span className={`palette-node-icon ${nodeTone(item.type)}`}>{nodeIcon(item.type)}</span><span><strong>{locale==="fa"?(labels[item.type]?.fa??item.type):(labels[item.type]?.en??item.type.replaceAll("_"," "))}</strong><small>{item.description??item.type.replaceAll("_"," ").toLowerCase()}</small></span><b aria-hidden>＋</b></button>)}</section>)}</aside>
   <div className="automation-canvas" aria-label={locale==="fa"?"بوم اتوماسیون":"Automation canvas"}>{flow.nodes.length?<ReactFlow nodeTypes={automationNodeTypes} edgeTypes={automationEdgeTypes} nodes={nodes} edges={edges} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onNodeClick={(_,n)=>setSelected(n.id)} nodesDraggable={canManage} nodesConnectable={canManage} edgesReconnectable={canManage} connectionRadius={45} fitView fitViewOptions={{padding:.22}} deleteKeyCode={canManage?["Backspace","Delete"]:null}><Background gap={22} size={1}/><Controls/><MiniMap pannable zoomable nodeColor={node=>node.data.type==="AI_OPERATION"?"#7c5cff":String(node.data.type).includes("TRIGGER")?"#2d8cff":"#57b98a"}/></ReactFlow>:<EmptyState title={locale==="fa"?"فلو خالی است":"Start your workflow"} description={locale==="fa"?"یک گره واقعی از فهرست اضافه کنید.":"Choose a runtime-supported trigger or action from the node library."}/>} {testOpen?<section className="automation-test-panel" aria-label={locale==="fa"?"اجرای آزمایشی":"Test run"}><header><div><span className="page-kicker">{locale==="fa"?"شبیه‌سازی":"Simulation"}</span><strong>{locale==="fa"?"اجرای آزمایشی با داده واقعی":"Run with scoped input"}</strong></div><button className="dialog-close" aria-label="Close test panel" onClick={()=>setTestOpen(false)} disabled={pending==="test"}>×</button></header><label><span>{locale==="fa"?"ورودی JSON":"JSON input"}</span><textarea dir="ltr" aria-invalid={Boolean(runInputError)} value={runInput} onChange={e=>{setRunInput(e.target.value);setRunInputError(null)}}/></label>{runInputError?<small className="field-error" role="alert">{runInputError}</small>:null}<footer><span>{flow.entryNodeId?`${locale==="fa"?"شروع":"Entry"}: ${flow.entryNodeId}`:(locale==="fa"?"گره شروع انتخاب نشده":"No entry node selected")}</span><AsyncButton pending={pending==="test"} pendingLabel={locale==="fa"?"در حال اجرا…":"Running…"} disabled={!flow.entryNodeId} onClick={test}>▶ {locale==="fa"?"اکنون اجرا کن":"Run now"}</AsyncButton></footer></section>:null}</div>
   <aside className={`automation-inspector ${selected!==null?"is-open":""}`}>{selectedNode?<><header><div className="inspector-node-heading"><span className={`palette-node-icon ${nodeTone(selectedNode.type)}`}>{nodeIcon(selectedNode.type)}</span><div><small>{selectedNode.type.replaceAll("_"," ")}</small><h2>{selectedNode.name}</h2></div></div><button aria-label="Close inspector" onClick={()=>setSelected(null)}>×</button></header><div className="inspector-tabs" role="tablist"><button role="tab" aria-selected="true">{locale==="fa"?"تنظیم":"Configure"}</button><button role="tab" aria-selected="false" disabled>{locale==="fa"?"ورودی":"Input"}</button><button role="tab" aria-selected="false" disabled>{locale==="fa"?"خروجی":"Output"}</button></div><label><span>{locale==="fa"?"نام":"Name"}</span><input value={selectedNode.name} onChange={e=>updateNode({name:e.target.value})}/></label><label className="toggle-row"><input type="checkbox" checked={selectedNode.enabled} onChange={e=>updateNode({enabled:e.target.checked})}/><span>{locale==="fa"?"فعال":"Enabled"}</span></label>{selectedNode.type==="AI_OPERATION"?<AiInspector node={selectedNode} updateNode={updateNode} locale={locale}/>:<JsonConfig node={selectedNode} updateNode={updateNode} locale={locale}/>}<Select label={locale==="fa"?"اعتبارنامه":"Credential reference"} value={selectedNode.credentialRef??""} onChange={e=>updateNode({credentialRef:e.target.value||null})}><option value="">{locale==="fa"?"بدون اعتبارنامه":"No credential"}</option>{credentials.map(c=><option value={c.id} key={c.id}>{c.name} · {c.type}</option>)}</Select><label><span>{locale==="fa"?"تلاش مجدد":"Retry attempts"}</span><input type="number" min="1" value={selectedNode.retryPolicy?.maxAttempts??1} onChange={e=>updateNode({retryPolicy:{...selectedNode.retryPolicy,maxAttempts:Number(e.target.value)}})}/></label><button className="danger-link" onClick={()=>setConfirmAction("delete-node")}>{locale==="fa"?"حذف گره":"Delete node"}</button></>:<WorkflowInspector flow={flow} setFlow={(next)=>{setFlow(next);setDirty(true)}} addConnection={addConnection} locale={locale}/>}</aside>
   {selected!==null?<button className="editor-sheet-close" aria-label={locale==="fa"?"بستن پنل":"Close editor panel"} onClick={()=>setSelected(null)}>×</button>:null}
  </div>
  <ConfirmDialog open={confirmAction==="activate"} title={locale==="fa"?"فعال‌سازی این نسخه؟":"Activate this version?"} body={locale==="fa"?"این نسخه برای اجراهای جدید استفاده خواهد شد.":"New executions will use this workflow version."} confirmLabel={locale==="fa"?"فعال‌سازی":"Activate"} pending={pending==="ACTIVATE"} onClose={()=>setConfirmAction(null)} onConfirm={()=>{setConfirmAction(null);void lifecycle("ACTIVATE")}}/>
  <ConfirmDialog open={confirmAction==="delete-node"} title={locale==="fa"?"حذف گره؟":"Delete this node?"} body={locale==="fa"?"اتصال‌های ورودی و خروجی این گره نیز حذف می‌شوند.":"Its incoming and outgoing connections will also be removed."} confirmLabel={locale==="fa"?"حذف گره":"Delete node"} onClose={()=>setConfirmAction(null)} onConfirm={()=>{setFlow(v=>({...v,nodes:v.nodes.filter(n=>n.id!==selected),edges:v.edges.filter(e=>e.fromNodeId!==selected&&e.toNodeId!==selected)}));setSelected(null);setDirty(true);setConfirmAction(null)}}/>
 </section>
}

function JsonConfig({node,updateNode,locale}:{node:AutomationFlow["nodes"][number];updateNode:(p:Record<string,unknown>)=>void;locale:string}){const [text,setText]=useState(JSON.stringify(node.config??{},null,2));useEffect(()=>setText(JSON.stringify(node.config??{},null,2)),[node.id]);return <label><span>{locale==="fa"?"پارامترها (JSON)":"Parameters (JSON)"}</span><textarea dir="ltr" value={text} onChange={e=>{setText(e.target.value);try{updateNode({config:JSON.parse(e.target.value)})}catch{}}}/></label>}
function AiInspector({node,updateNode,locale}:{node:AutomationFlow["nodes"][number];updateNode:(p:Record<string,unknown>)=>void;locale:string}){const config=node.config;const set=(key:string,value:unknown)=>updateNode({config:{...config,[key]:value}});return <div className="ai-node-fields"><Select label={locale==="fa"?"عملیات":"Operation"} value={String(config.operation??"TRANSFORM_DATA")} onChange={e=>set("operation",e.target.value)}><option value="TRANSFORM_DATA">Transform data</option><option value="GENERATE_CONTENT">Generate content</option><option value="GENERATE_DSL">Generate platform DSL</option></Select><label><span>{locale==="fa"?"دستورالعمل":"Instructions"}</span><textarea value={String(config.instructions??"")} onChange={e=>set("instructions",e.target.value)} placeholder={locale==="fa"?"عملیات موردنظر را دقیق توضیح دهید":"Describe the operation precisely"}/></label><label><span>{locale==="fa"?"ورودی / عبارت":"Input / expression"}</span><textarea dir="ltr" value={typeof config.input==="string"?config.input:JSON.stringify(config.input??{},null,2)} onChange={e=>set("input",e.target.value)}/></label><label><span>{locale==="fa"?"مسیر نتیجه":"Result path"}</span><input dir="ltr" value={String(config.resultPath??"aiResult")} onChange={e=>set("resultPath",e.target.value)}/></label><small>{locale==="fa"?"این گره فقط با ارائه‌دهنده هوش پیکربندی‌شده اجرا می‌شود.":"This node runs only when an AI provider is configured."}</small></div>}
function WorkflowInspector({flow,setFlow,addConnection,locale}:{flow:AutomationFlow;setFlow:(f:AutomationFlow)=>void;addConnection:(fromNodeId:string,toNodeId:string)=>void;locale:string}){const [from,setFrom]=useState(flow.nodes[0]?.id??"");const [to,setTo]=useState(flow.nodes[1]?.id??"");return <><header><div><small>{locale==="fa"?"تنظیمات":"Workflow settings"}</small><h2>{flow.name||"—"}</h2></div></header><label><span>{locale==="fa"?"کلید فلو":"Flow key"}</span><input dir="ltr" value={flow.flowKey} disabled={Boolean(flow.id)} onChange={e=>setFlow({...flow,flowKey:e.target.value})}/></label><label><span>{locale==="fa"?"نام":"Name"}</span><input value={flow.name} onChange={e=>setFlow({...flow,name:e.target.value})}/></label><Select label={locale==="fa"?"حالت اجرا":"Runtime mode"} value={flow.runtimeMode} onChange={e=>setFlow({...flow,runtimeMode:e.target.value as AutomationFlow["runtimeMode"]})}><option value="VARIABLES">VARIABLES</option><option value="N8N_ITEMS">N8N_ITEMS</option></Select><label><span>{locale==="fa"?"گره شروع":"Entry node"}</span><select value={flow.entryNodeId} onChange={e=>setFlow({...flow,entryNodeId:e.target.value})}><option value="">—</option>{flow.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><section className="workflow-connection-builder"><header><strong>{locale==="fa"?"افزودن اتصال":"Add connection"}</strong><small>{locale==="fa"?"جایگزین قابل‌دسترسی برای کشیدن خط":"Accessible alternative to drawing a line"}</small></header><div><select aria-label={locale==="fa"?"از":"From"} value={from} onChange={e=>setFrom(e.target.value)}>{flow.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select><span aria-hidden>→</span><select aria-label={locale==="fa"?"به":"To"} value={to} onChange={e=>setTo(e.target.value)}>{flow.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></div><button className="secondary-pill" disabled={!from||!to||from===to} onClick={()=>addConnection(from,to)}>＋ {locale==="fa"?"اتصال":"Connect"}</button></section><details><summary>{locale==="fa"?"پیشرفته":"Advanced"}</summary><CodeViewer value={flow}/></details></>}
