spring.config.import=optional:file:.env[.properties]
server.port=8010

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${LEGACY_DB_URL:jdbc:postgresql://localhost:5432/client_service}
spring.datasource.username=${LEGACY_DB_USERNAME:postgres}
spring.datasource.password=${LEGACY_DB_PASSWORD:postgres}
spring.jpa.show-sql=true


spring.main.allow-bean-definition-overriding=true

feign.client.config.default.loggerLevel=BASIC

logging.level.com.cyan.open_exchange.client.web.rest.*=DEBUG

feign.httpclient.enabled= true
feign.okhttp.enabled= true


eureka.client.serviceUrl.defaultZone=http://admin:CyanAdmin@localhost:8761/eureka
spring.application.name=client-service
spring.data.mongodb.uri=mongodb://localhost:27017/client_service
spring.data.mongodb.auto-index-creation=true
service.internal.username=client_internal
service.internal.password=client_secret
dynamic.runtime.service-key=client-service
dynamic.runtime.check-missing-fields=true
dynamic.runtime.check-extra-fields=true




server.error.include-message=always
server.error.include-binding-errors=always

axon.eventhandling.processors.factorModel-group.mode=subscribing

axon.axonserver.token=123cba

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/.well-known/jwks.json
