"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { PanelShell } from "@/components/panel-shell";
import { usePanel } from "@/components/panel-provider";
import { useScopeAccess } from "@/components/scope-access-provider";
import { EmptyState, ErrorState, Skeleton, StatusBadge } from "@/components/ui/primitives";
import { listInbox, markAllNotificationsRead, markNotificationRead, type InboxNotification } from "@/lib/notification-api";
export default function NotificationsPage(){const {locale}=usePanel();const {tenantKey,queryVersion}=useScopeAccess();const [items,setItems]=useState<InboxNotification[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);async function load(){if(!tenantKey){setLoading(false);return;}setLoading(true);setError(null);try{setItems((await listInbox()).content);}catch(e){setError(e instanceof Error?e.message:"Notifications could not be loaded.");}finally{setLoading(false);}}useEffect(()=>{void load();},[tenantKey,queryVersion]);async function read(item:InboxNotification){if(!item.readAt){const value=await markNotificationRead(item.notificationId);setItems(v=>v.map(x=>x.notificationId===value.notificationId?value:x));}}return <PanelShell activeKey="notifications" title="Notifications" titleFa="اعلان‌ها" subtitle="Your scoped operational inbox." subtitleFa="صندوق اعلان‌های عملیاتی شما در محدوده فعال."><section className="notification-page"><header><div><h2>{locale==="fa"?"صندوق ورودی":"Inbox"}</h2><p>{items.filter(x=>!x.readAt).length} {locale==="fa"?"خوانده‌نشده":"unread"}</p></div>{items.some(x=>!x.readAt)?<button className="secondary-pill" onClick={async()=>{await markAllNotificationsRead();await load();}}>{locale==="fa"?"خواندن همه":"Mark all read"}</button>:null}</header>{loading?<><Skeleton height={76}/><Skeleton height={76}/></>:error?<ErrorState title={locale==="fa"?"اعلان‌ها در دسترس نیست":"Notifications unavailable"} description={error} retry={load}/>:items.length?<div className="notification-page-list">{items.map(item=><article key={item.notificationId} className={item.readAt?"notification-row":"notification-row unread"}><button onClick={()=>void read(item)} aria-label={locale==="fa"?"علامت‌گذاری به‌عنوان خوانده‌شده":"Mark as read"}><span className="notification-dot"/><div><strong>{item.title}</strong>{item.body?<p>{item.body}</p>:null}<time>{new Date(item.createdAt).toLocaleString(locale)}</time></div><StatusBadge tone={item.severity==="ERROR"?"danger":item.severity==="WARNING"?"warning":"info"}>{item.type}</StatusBadge></button>{item.deepLink?<Link href={item.deepLink}>{locale==="fa"?"باز کردن":"Open"}</Link>:null}</article>)}</div>:<EmptyState title={locale==="fa"?"اعلانی نیست":"No notifications"} description={locale==="fa"?"سرویس هیچ اعلان واقعی برای این محدوده برنگرداند.":"The service returned no notifications for this scope."}/>}</section></PanelShell>}
