server.port=9129
spring.application.name=tenant-service
eureka.client.serviceUrl.defaultZone=http://admin:CyanAdmin@localhost:8761/eureka
spring.datasource.url=jdbc:h2:file:./data/tenant-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/.well-known/jwks.json
service.internal.username=tenant_internal
service.internal.password=tenant_secret
billing.service.base-url=http://localhost:9130
billing.service.internal.username=billing_internal
billing.service.internal.password=billing_secret
platform.openapi.default-security=BEARER
