package com.cyancoder.media.service;
import com.cyancoder.dynamiccore.runtime.DynamicScope;import com.cyancoder.media.model.MediaAssetContracts.*;import com.cyancoder.media.model.MediaUploadEntity;import com.cyancoder.media.repository.MediaUploadRepository;import java.nio.file.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.core.io.Resource;import org.springframework.core.io.UrlResource;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.web.server.ResponseStatusException;
@Service public class MediaOperatorService{private final MediaUploadRepository uploads;private final MediaAssetService assets;private final TenantMembershipClient memberships;private final Path root;public MediaOperatorService(MediaUploadRepository u,MediaAssetService a,TenantMembershipClient m,@Value("${media.storage.root}")String r){uploads=u;assets=a;memberships=m;root=Path.of(r).toAbsolutePath().normalize();}
 public AssetPage list(String tenant,String site,String actor,String q,String type,String status,int page,int size){memberships.requireMembership(tenant,actor);String s=blank(site),needle=q==null?"":q.trim().toLowerCase();List<AssetItem> all=uploads.findAllByTenantKeyAndSiteKeyOrderByCreatedAtDesc(tenant,s).stream().filter(x->needle.isBlank()||x.getOriginalFileName().toLowerCase().contains(needle)||x.getAssetKey().contains(needle)).filter(x->type==null||type.isBlank()||mediaType(x.getMimeType()).equalsIgnoreCase(type)).filter(x->status==null||status.isBlank()||x.getStatus().equalsIgnoreCase(status)).map(this::item).toList();int safe=Math.max(1,Math.min(100,size)),from=Math.min(Math.max(0,page)*safe,all.size());return new AssetPage(all.subList(from,Math.min(from+safe,all.size())),Math.max(0,page),safe,all.size());}
 public AssetItem get(String tenant,String site,String actor,String key){memberships.requireMembership(tenant,actor);return item(scoped(key,tenant,site));}
 public AssetItem update(String tenant,String site,String actor,String key,UpdateAssetRequest r){memberships.requireMembership(tenant,actor);MediaUploadEntity u=scoped(key,tenant,site);Map<String,Object> seo=new LinkedHashMap<>();seo.put("title",n(r.title(),u.getOriginalFileName()));seo.put("altText",n(r.altText(),u.getOriginalFileName()));seo.put("caption",n(r.caption(),""));seo.put("license",n(r.license(),""));Map<String,Object> changes=new LinkedHashMap<>();changes.put("seo",seo);changes.put("tags",r.tags()==null?List.of():r.tags().stream().filter(Objects::nonNull).map(String::trim).filter(x->!x.isBlank()).distinct().toList());changes.put("folderKey",n(r.folderKey(),""));if(r.visibility()!=null&&!r.visibility().isBlank()){String v=r.visibility().toUpperCase(Locale.ROOT);if(!Set.of("PUBLIC","PRIVATE").contains(v))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"visibility must be PUBLIC or PRIVATE");u.setVisibility(v);uploads.save(u);changes.put("visibility",v);}assets.update(key,changes,new DynamicScope(tenant,blank(site)));return item(u);}
 public UsageResponse usage(String tenant,String site,String actor,String key){get(tenant,site,actor,key);return new UsageResponse(key,"UNKNOWN",0,List.of(),"A platform reverse-reference registry is not configured; deletion is protected.");}
 public Resource privateContent(String tenant,String site,String actor,String key){memberships.requireMembership(tenant,actor);return resource(scoped(key,tenant,site),false);}
 public Resource publicContent(String key){MediaUploadEntity u=uploads.findByAssetKey(key).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset not found"));return resource(u,true);}
 public MediaUploadEntity publicMetadata(String key){MediaUploadEntity u=uploads.findByAssetKey(key).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset not found"));if(!"PUBLIC".equals(u.getVisibility())||!"UPLOADED".equals(u.getStatus()))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset not found");return u;}
 private Resource resource(MediaUploadEntity u,boolean publicly){if(!"UPLOADED".equals(u.getStatus())||(publicly&&!"PUBLIC".equals(u.getVisibility())))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset content not found");try{Path p=Path.of(u.getStoragePath()).toAbsolutePath().normalize();if(!p.startsWith(root)||!Files.isRegularFile(p))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset content not found");return new UrlResource(p.toUri());}catch(ResponseStatusException e){throw e;}catch(Exception e){throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset content not found",e);}}
 private MediaUploadEntity scoped(String key,String tenant,String site){return uploads.findByAssetKeyAndTenantKeyAndSiteKey(key,tenant,blank(site)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Asset not found"));}private AssetItem item(MediaUploadEntity u){Map<String,Object>meta;try{meta=assets.get(u.getAssetKey(),new DynamicScope(u.getTenantKey(),u.getSiteKey())).data();}catch(Exception e){meta=Map.of();}String url="UPLOADED".equals(u.getStatus())?(("PUBLIC".equals(u.getVisibility())?"/public/media/content/":"/endpoint/media/assets/")+u.getAssetKey()+("PUBLIC".equals(u.getVisibility())?"":"/content")):null;return new AssetItem(u.getAssetKey(),u.getOriginalFileName(),u.getMimeType(),mediaType(u.getMimeType()),u.getVisibility(),u.getUploadedSizeBytes(),u.getStatus(),url,u.getCreatedAt(),u.getCompletedAt(),meta);}private String mediaType(String m){if(m.startsWith("image/"))return"IMAGE";if(m.startsWith("video/"))return"VIDEO";if(m.startsWith("audio/"))return"AUDIO";if(m.equals("application/pdf")||m.startsWith("text/"))return"DOCUMENT";return"OTHER";}private String blank(String v){return v==null||v.isBlank()?null:v;}private String n(String v,String d){return v==null?d:v.trim();}}
