package com.cyancoder.aiorchestrator.domain;

import com.cyancoder.aiorchestrator.api.dto.AiOperationRequest;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Version;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.mapping.Document;

@Document("ai_artifact_jobs") @CompoundIndex(name="ai_artifact_scope_created",def="{'tenantKey':1,'siteKey':1,'createdAt':-1}")
public class AiArtifactJob {
 @Id private String jobId; @Version private Long revision; private String tenantKey; private String siteKey; private String actor; private String status; private AiOperationRequest.AiOperationType operation; private String instructions; private Object input; private String providerProfileKey; private List<AiOperationRequest.AiAssetInput> assets; private String requestedMimeType; private String fileName; private Integer retentionDays; private String assetKey; private String deliveryUrl; private Map<String,Object> usage; private String errorCode; private String errorMessage; private Instant createdAt; private Instant startedAt; private Instant completedAt;
 public String getJobId(){return jobId;}public void setJobId(String v){jobId=v;}public Long getRevision(){return revision;}public void setRevision(Long v){revision=v;}public String getTenantKey(){return tenantKey;}public void setTenantKey(String v){tenantKey=v;}public String getSiteKey(){return siteKey;}public void setSiteKey(String v){siteKey=v;}public String getActor(){return actor;}public void setActor(String v){actor=v;}public String getStatus(){return status;}public void setStatus(String v){status=v;}public AiOperationRequest.AiOperationType getOperation(){return operation;}public void setOperation(AiOperationRequest.AiOperationType v){operation=v;}public String getInstructions(){return instructions;}public void setInstructions(String v){instructions=v;}public Object getInput(){return input;}public void setInput(Object v){input=v;}public String getProviderProfileKey(){return providerProfileKey;}public void setProviderProfileKey(String v){providerProfileKey=v;}public List<AiOperationRequest.AiAssetInput> getAssets(){return assets;}public void setAssets(List<AiOperationRequest.AiAssetInput> v){assets=v;}public String getRequestedMimeType(){return requestedMimeType;}public void setRequestedMimeType(String v){requestedMimeType=v;}public String getFileName(){return fileName;}public void setFileName(String v){fileName=v;}public Integer getRetentionDays(){return retentionDays;}public void setRetentionDays(Integer v){retentionDays=v;}public String getAssetKey(){return assetKey;}public void setAssetKey(String v){assetKey=v;}public String getDeliveryUrl(){return deliveryUrl;}public void setDeliveryUrl(String v){deliveryUrl=v;}public Map<String,Object> getUsage(){return usage;}public void setUsage(Map<String,Object> v){usage=v;}public String getErrorCode(){return errorCode;}public void setErrorCode(String v){errorCode=v;}public String getErrorMessage(){return errorMessage;}public void setErrorMessage(String v){errorMessage=v;}public Instant getCreatedAt(){return createdAt;}public void setCreatedAt(Instant v){createdAt=v;}public Instant getStartedAt(){return startedAt;}public void setStartedAt(Instant v){startedAt=v;}public Instant getCompletedAt(){return completedAt;}public void setCompletedAt(Instant v){completedAt=v;}
}
