spring.application.name=bpm-service
server.port=9119

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.data.mongodb.uri=mongodb://localhost:27017/bpm_service

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/.well-known/jwks.json

service.internal.username=bpm_internal
service.internal.password=bpm_secret

