spring.application.name=bpm-service
server.port=9119

eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.data.mongodb.uri=mongodb://localhost:27017/bpm_service

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/.well-known/jwks.json

service.internal.username=bpm_internal
service.internal.password=bpm_secret

