server.port=9124
spring.application.name=pricing-promotion-service
eureka.client.serviceUrl.defaultZone=http://admin:CyanAdmin@localhost:8761/eureka
spring.datasource.url=jdbc:postgresql://localhost:5432/pricing_promotion_service
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.data.mongodb.uri=mongodb://localhost:27017/pricing_promotion_service
spring.data.mongodb.auto-index-creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/.well-known/jwks.json
service.internal.username=pricing_promotion_internal
service.internal.password=pricing_promotion_secret
dynamic.runtime.service-key=pricing-promotion-service
dynamic.runtime.check-missing-fields=true
dynamic.runtime.check-extra-fields=true
