eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
spring.datasource.url=${BILLING_SERVICE_DATASOURCE_URL:jdbc:postgresql://postgres:5432/billing_service}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${BILLING_SERVICE_DATASOURCE_USERNAME:${SPRING_DATASOURCE_USERNAME:postgres}}
spring.datasource.password=${BILLING_SERVICE_DATASOURCE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:postgres}}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_URI:http://sso-auth-service:9001/.well-known/jwks.json}
service.internal.username=${BILLING_SERVICE_INTERNAL_USERNAME:billing_internal}
service.internal.password=${BILLING_SERVICE_INTERNAL_PASSWORD:billing_secret}
tenant.service.base-url=${TENANT_SERVICE_BASE_URL:http://tenant-service:9129}
