"use client";
import Link from "next/link";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { PanelShell } from "@/components/panel-shell";
import { usePanel } from "@/components/panel-provider";
import { useScopeAccess } from "@/components/scope-access-provider";
import { EmptyState, ErrorState, Skeleton, StatusBadge } from "@/components/ui/primitives";
import { listAssignedManagedObjects, type ManagedObject } from "@/lib/bpm-api";
import { listBotIntegrations, listClientDrafts, listProvisioningRuns } from "@/lib/platform-api";
import { listAutomationExecutions } from "@/lib/service-api";
import { getUnreadCount } from "@/lib/notification-api";
import type { AutomationExecution, BotChannelIntegration, ClientAppDraft, ProvisioningRun } from "@/lib/types";

type Bucket<T>={data:T;loading:boolean;error:string|null;updatedAt:string|null}; const bucket=<T,>(data:T):Bucket<T>=>({data,loading:true,error:null,updatedAt:null});
export default function Dashboard(){
 const {locale}=usePanel(); const {bootstrap,tenantKey,siteKey,queryVersion,can,hasCapability}=useScopeAccess(); const [drafts,setDrafts]=useState(bucket<ClientAppDraft[]>([])); const [work,setWork]=useState(bucket<ManagedObject[]>([])); const [automations,setAutomations]=useState(bucket<AutomationExecution[]>([])); const [bots,setBots]=useState(bucket<BotChannelIntegration[]>([])); const [runs,setRuns]=useState(bucket<ProvisioningRun[]>([])); const [unread,setUnread]=useState(bucket<number|null>(null));
 const scope=useMemo(()=>({tenantKey:tenantKey||undefined,siteKey:siteKey||undefined}),[tenantKey,siteKey]);
 useEffect(()=>{if(!tenantKey)return; let live=true; const load=<T,>(fn:()=>Promise<T>,set:(v:Bucket<T>)=>void,initial:T)=>{set(bucket(initial));fn().then(data=>live&&set({data,loading:false,error:null,updatedAt:new Date().toISOString()})).catch(e=>live&&set({data:initial,loading:false,error:e instanceof Error?e.message:"Unavailable",updatedAt:null}));};load(()=>listClientDrafts(scope),setDrafts,[]);if(hasCapability("bpm")&&can("bpm.read"))load(()=>listAssignedManagedObjects(scope),setWork,[]);else setWork({data:[],loading:false,error:null,updatedAt:null});if(hasCapability("automation")&&can("automation.read"))load(()=>listAutomationExecutions(scope),setAutomations,[]);else setAutomations({data:[],loading:false,error:null,updatedAt:null});if(hasCapability("bot-adapter")&&can("bot.read"))load(()=>listBotIntegrations(scope),setBots,[]);else setBots({data:[],loading:false,error:null,updatedAt:null});load(()=>getUnreadCount().then(value=>value.unreadCount),setUnread,null);return()=>{live=false};},[queryVersion,tenantKey,siteKey,scope,can,hasCapability]);
 const latest=useMemo(()=>[...drafts.data].sort((a,b)=>Date.parse(b.updatedAt||"")-Date.parse(a.updatedAt||""))[0]||null,[drafts.data]);
 useEffect(()=>{if(!latest){setRuns({data:[],loading:false,error:null,updatedAt:null});return;}setRuns(bucket([]));listProvisioningRuns(latest.draftId).then(data=>setRuns({data,loading:false,error:null,updatedAt:new Date().toISOString()})).catch(e=>setRuns({data:[],loading:false,error:e instanceof Error?e.message:"Unavailable",updatedAt:null}));},[latest?.draftId]);
 const capabilities=bootstrap?.capabilities.filter(c=>c.enabled)??[]; const failed=automations.data.filter(x=>String(x.status).toUpperCase()==="FAILED"); const activity=[...drafts.data.map(item=>({id:item.draftId,label:item.title,status:item.status,at:item.updatedAt,href:`/projects/${item.draftId}`})),...runs.data.map(item=>({id:item.runId,label:item.runId,status:item.status,at:item.startedAt,href:latest?`/projects/${latest.draftId}`:"/projects"}))].sort((a,b)=>Date.parse(b.at||"")-Date.parse(a.at||"")).slice(0,5);
 return <PanelShell activeKey="dashboard" title="Workspace overview" titleFa="نمای کلی فضای کار" subtitle="Resume work and monitor real platform operations." subtitleFa="کار را ادامه دهید و وضعیت واقعی پلتفرم را پایش کنید."><div className="phase-dashboard">
  <section className="active-project-card">{drafts.loading?<Skeleton height={190}/>:drafts.error?<ErrorState title="Projects unavailable" description={drafts.error}/>:latest?<><div><StatusBadge tone="info">{latest.status}</StatusBadge><h2>{latest.title}</h2><p>{latest.latestIntent}</p><div className="metric-pills"><span>{latest.resolvedDsl?.entities?.length??0} {locale==="fa"?"موجودیت":"entities"}</span><span>{latest.resolvedDsl?.routes?.length??0} {locale==="fa"?"مسیر":"routes"}</span><span>{latest.resolvedDsl?.flows?.length??0} {locale==="fa"?"فلو":"flows"}</span></div><Link className="primary-pill" href={`/projects/${latest.draftId}`}>{locale==="fa"?"ادامه ساخت":"Continue building"}</Link></div></>:<EmptyState title={locale==="fa"?"پروژه فعالی نیست":"No active project"} description={locale==="fa"?"از استودیوی هوش یا یک قالب واقعی شروع کنید.":"Start with AI Studio or an available blueprint."} action={<Link className="primary-pill" href="/ai">{locale==="fa"?"شروع":"Start building"}</Link>}/>}</section>
  <section className="dashboard-result-links" aria-labelledby="result-links-title"><header><div><p className="page-kicker">{locale==="fa"?"خروجی‌های فضای کاری":"Workspace results"}</p><h2 id="result-links-title">{locale==="fa"?"ساخته‌های خود را باز کنید":"Open what your team built"}</h2></div></header><div>{hasCapability("bpm")&&can("bpm.read")?<Link href="/work"><span aria-hidden>⌁</span><div><strong>{locale==="fa"?"کارتابل من":"My cartable"}</strong><small>{locale==="fa"?"کارها، فرم‌های فعال و انتقال‌ها":"Assigned work, active forms, and transitions"}</small></div><b>→</b></Link>:null}{hasCapability("dynamic-entities")?<Link href="/forms"><span aria-hidden>▤</span><div><strong>{locale==="fa"?"فرم‌های من":"My forms"}</strong><small>{locale==="fa"?"فرم‌های خصوصی و پیوندهای عمومی":"Private forms and public links"}</small></div><b>→</b></Link>:null}{hasCapability("dynamic-entities")&&can("record.read")?<Link href="/data"><span aria-hidden>◫</span><div><strong>{locale==="fa"?"داده و فرم موجودیت":"Entity data & forms"}</strong><small>{locale==="fa"?"رکوردها و فرم ایجاد رکورد":"Records and generated record forms"}</small></div><b>→</b></Link>:null}{hasCapability("bpm")&&can("bpm.read")?<Link href="/bpm"><span aria-hidden>◇</span><div><strong>{locale==="fa"?"طراح فرایند":"BPM designer"}</strong><small>{locale==="fa"?"تعریف و انتشار فرایندها":"Design and publish processes"}</small></div><b>→</b></Link>:null}{hasCapability("site-builder")&&can("site.read")?<Link href="/sites"><span aria-hidden>▣</span><div><strong>{locale==="fa"?"سایت‌ها و پیش‌نمایش":"Sites & previews"}</strong><small>{locale==="fa"?"سازنده، سایت عمومی و کارتابل سایت":"Builder, public site, and site portal"}</small></div><b>→</b></Link>:null}</div>{bootstrap?.sites.length?<footer>{bootstrap.sites.map(site=><span key={site.siteKey}><strong>{site.name}</strong><Link href={`/sites/${encodeURIComponent(site.siteKey)}/portal`}>{locale==="fa"?"کارتابل سایت":"Site cartable"}</Link><Link href={`/sites/${encodeURIComponent(site.siteKey)}/builder`}>{locale==="fa"?"سازنده و پیش‌نمایش":"Builder & preview"}</Link></span>)}</footer>:null}</section>
  <div className="dashboard-widget-grid"><Widget title={locale==="fa"?"پروژه‌های اخیر":"Recent projects"} state={drafts}>{drafts.data.slice(0,5).map(x=><Link key={x.draftId} href={`/projects/${x.draftId}`}><strong>{x.title}</strong><span>{x.status}</span></Link>)}</Widget><Widget title={locale==="fa"?"اجرای استقرار":"Provisioning runs"} state={runs}>{runs.data.slice(0,5).map(x=><div key={x.runId}><strong>{x.runId}</strong><span>{x.status}</span></div>)}</Widget>{hasCapability("bpm")&&can("bpm.read")?<Widget title={locale==="fa"?"کارهای واگذارشده":"Assigned work"} state={work}>{work.data.slice(0,5).map(x=><Link key={x.id} href={`/work/${x.id}`}><strong>{x.objectType}</strong><span>{x.state}</span></Link>)}</Widget>:null}{hasCapability("automation")&&can("automation.read")?<Widget title={locale==="fa"?"خطاهای اتوماسیون":"Automation failures"} state={automations}>{failed.slice(0,5).map((x,i)=><Link key={String(x.executionId||i)} href="/automations"><strong>{String(x.automationFlowKey||x.automationKey||x.executionId)}</strong><span>{String(x.status)}</span></Link>)}</Widget>:null}<Widget title={locale==="fa"?"قابلیت‌های فعال":"Active capabilities"} state={{data:capabilities,loading:!bootstrap,error:null,updatedAt:new Date().toISOString()}}>{capabilities.map(x=><div key={x.key}><strong>{x.key}</strong><StatusBadge tone={x.status==="AVAILABLE"?"success":"warning"}>{x.status}</StatusBadge></div>)}</Widget><Widget title={locale==="fa"?"بات‌ها و سایت‌ها":"Bots and sites"} state={bots}>{bots.data.filter(x=>x.active).map(x=><Link key={`${x.channel}-${x.integrationKey}`} href="/bots"><strong>{x.integrationKey}</strong><span>{x.channel}</span></Link>)}{bootstrap?.sites.map(x=><Link key={x.siteKey} href={`/sites/${encodeURIComponent(x.siteKey)}/builder`}><strong>{x.name}</strong><span>{x.status}</span></Link>)}</Widget><Widget title={locale==="fa"?"اعلان‌ها":"Notifications"} state={unread}>{unread.data!==null?<Link href="/notifications"><strong>{unread.data}</strong><span>{locale==="fa"?"خوانده‌نشده":"unread"}</span></Link>:null}</Widget><Widget title={locale==="fa"?"محدودیت‌های پلن":"Plan limits"} state={{data:bootstrap?.subscription?.limits??{},loading:!bootstrap,error:null,updatedAt:null}}>{Object.entries(bootstrap?.subscription?.limits??{}).map(([key,value])=><div key={key}><strong>{key}</strong><span>{String(value)}</span></div>)}</Widget><Widget title={locale==="fa"?"فعالیت اخیر":"Recent activity"} state={{data:activity,loading:drafts.loading||runs.loading,error:drafts.error||runs.error,updatedAt:drafts.updatedAt}}>{activity.map(item=><Link key={item.id} href={item.href}><strong>{item.label}</strong><span>{item.status}</span></Link>)}</Widget></div>
  {bootstrap?.subscription?.status==="NONE"?<section className="limited-dashboard"><h2>{locale==="fa"?"دسترسی محدود":"Limited access"}</h2><p>{locale==="fa"?"پلن فعالی ثبت نشده است. عملیات قفل‌شده موفقیت جعلی نمایش نمی‌دهند.":"No active plan is registered. Locked operations remain unavailable and never simulate success."}</p></section>:null}
 </div></PanelShell>;
}
function Widget<T>({title,state,children}:{title:string;state:Bucket<T>;children:ReactNode}){return <section className="dashboard-widget"><header><h3>{title}</h3>{state.updatedAt?<time>{new Date(state.updatedAt).toLocaleTimeString()}</time>:null}</header>{state.loading?<><Skeleton height={45}/><Skeleton height={45}/></>:state.error?<ErrorState title="Unavailable" description={state.error}/>:children||<EmptyState title="No data" description="The service returned no records."/>}</section>}
