"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { PanelShell } from "@/components/panel-shell";
import { EmptyState,ErrorState,Skeleton,StatusBadge } from "@/components/ui/primitives";
import { usePanel } from "@/components/panel-provider";
import { useScopeAccess } from "@/components/scope-access-provider";
import { listAutomationFlows,listExecutions,type AutomationExecution,type AutomationFlow } from "@/lib/automation-api";
export default function AutomationsPage(){const {locale}=usePanel();const {tenantKey,siteKey,queryVersion}=useScopeAccess();const [flows,setFlows]=useState<AutomationFlow[]>([]);const [runs,setRuns]=useState<AutomationExecution[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [query,setQuery]=useState("");const load=async()=>{if(!tenantKey){setLoading(false);return}setLoading(true);setError(null);try{const [f,r]=await Promise.all([listAutomationFlows(),listExecutions()]);setFlows(f);setRuns(r)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}};useEffect(()=>{void load()},[tenantKey,siteKey,queryVersion]);const latest=useMemo(()=>Array.from(new Map(flows.map(f=>[f.flowKey,f])).values()).filter(f=>`${f.name} ${f.flowKey}`.toLowerCase().includes(query.toLowerCase())),[flows,query]);return <PanelShell activeKey="automation" title="Automations" titleFa="اتوماسیون‌ها" subtitle="Design, schedule, run, and diagnose service-backed workflows." subtitleFa="طراحی، زمان‌بندی، اجرا و بررسی جریان‌های واقعی."><div className="page-action-bar"><div><input aria-label="Search automations" value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==="fa"?"جستجوی اتوماسیون":"Search automations"}/></div><div><Link className="secondary-pill" href="/automations/executions">{locale==="fa"?"اجراها":"Executions"}</Link><Link className="primary-pill" href="/automations/new">{locale==="fa"?"اتوماسیون جدید":"New automation"}</Link></div></div>{loading?<div className="catalog-skeleton"><Skeleton height={88}/><Skeleton height={88}/></div>:error?<ErrorState title={locale==="fa"?"اتوماسیون‌ها در دسترس نیستند":"Automations unavailable"} description={error} retry={load}/>:!tenantKey?<EmptyState title={locale==="fa"?"فضای کار انتخاب نشده":"No workspace selected"} description={locale==="fa"?"ابتدا فضای کار را انتخاب کنید.":"Select a workspace before loading automations."}/>:latest.length?<div className="automation-catalog">{latest.map(flow=>{const last=runs.find(r=>r.automationFlowKey===flow.flowKey);return <Link href={`/automations/${encodeURIComponent(flow.flowKey)}?version=${flow.version}`} key={`${flow.flowKey}-${flow.version}`}><div><strong>{flow.name}</strong><code dir="ltr">{flow.flowKey}</code></div><span>v{flow.version}</span><StatusBadge tone={flow.active?"success":"neutral"}>{flow.lifecycleStatus}</StatusBadge><span>{flow.nextScheduledAt?new Date(flow.nextScheduledAt).toLocaleString(locale):locale==="fa"?"بدون زمان‌بندی":"No schedule"}</span><span>{last?last.status:locale==="fa"?"اجرا نشده":"Not run"}</span></Link>})}</div>:<EmptyState title={locale==="fa"?"اتوماسیونی نیست":"No automations"} description={locale==="fa"?"سرویس برای این محدوده فلو برنگرداند.":"The service returned no flows for this scope."} action={<Link className="primary-pill" href="/automations/new">{locale==="fa"?"ایجاد اتوماسیون":"Create automation"}</Link>}/>}</PanelShell>}
