"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { PanelShell } from "@/components/panel-shell";
import { usePanel } from "@/components/panel-provider";
import { useScopeAccess } from "@/components/scope-access-provider";
import { AsyncButton, CodeViewer, ConfirmDialog, ErrorState, Skeleton, StatusBadge } from "@/components/ui/primitives";
import { cancelExecution, getExecution, retryExecution, type AutomationExecution } from "@/lib/automation-api";

export default function ExecutionDetail({ params }: { params: { executionId: string } }) {
  const { locale } = usePanel(); const { tenantKey, siteKey, queryVersion, can } = useScopeAccess();
  const scope = useMemo(() => ({ tenantKey: tenantKey ?? undefined, siteKey: siteKey ?? undefined }), [tenantKey, siteKey]); const canExecute = can("automation.execute");
  const [item, setItem] = useState<AutomationExecution | null>(null); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState<string | null>(null); const [cancelOpen, setCancelOpen] = useState(false);
  const status = item?.status;
  const load = useCallback(() => { if (!tenantKey) return Promise.resolve(); return getExecution(params.executionId, scope).then(setItem).catch(cause => setError(cause instanceof Error ? cause.message : String(cause))); }, [params.executionId, scope, tenantKey]);
  useEffect(() => { void load(); }, [load, queryVersion]);
  useEffect(() => { if (!status || !["RUNNING", "WAITING", "WAITING_CALLBACK"].includes(status)) return; const id = window.setInterval(() => void load(), 2500); return () => window.clearInterval(id); }, [load, status]);
  const action = async (kind: "cancel" | "retry") => { if (pending || !canExecute) return; setPending(kind); setError(null); try { setItem(kind === "cancel" ? await cancelExecution(params.executionId, scope) : await retryExecution(params.executionId, scope)); setCancelOpen(false); } catch (cause) { setError(cause instanceof Error ? cause.message : String(cause)); } finally { setPending(null); } };
  return <PanelShell activeKey="automation" title="Execution detail" titleFa="جزئیات اجرا" subtitle={params.executionId} subtitleFa={params.executionId}>{error ? <ErrorState title="Execution unavailable" description={error} retry={load}/> : !item ? <Skeleton height={560}/> : <div className="execution-detail"><div className="page-action-bar"><div><StatusBadge tone={item.status === "FAILED" ? "danger" : item.status === "COMPLETED" ? "success" : "info"}>{item.status}</StatusBadge><span>{item.automationFlowKey}</span></div><div>{canExecute && ["RUNNING", "WAITING", "WAITING_CALLBACK"].includes(item.status) ? <button className="secondary-pill" disabled={Boolean(pending)} onClick={() => setCancelOpen(true)}>{locale === "fa" ? "لغو" : "Cancel"}</button> : null}{canExecute && item.status === "FAILED" ? <AsyncButton pending={pending === "retry"} onClick={() => action("retry")}>{locale === "fa" ? "تلاش مجدد" : "Retry failed node"}</AsyncButton> : null}</div></div><section><h2>{locale === "fa" ? "مراحل" : "Steps"}</h2><div className="execution-timeline">{(item.steps ?? []).map((step, index) => <article key={index}><span/><div><strong>{String(step.nodeId ?? "—")}</strong><small>{String(step.nodeType ?? "")} · {String(step.status ?? "")}</small>{step.errorSnapshot ? <CodeViewer value={step.errorSnapshot}/> : null}</div></article>)}</div></section><section className="execution-io"><div><h2>Input</h2><CodeViewer value={item.input ?? {}}/></div><div><h2>Output</h2><CodeViewer value={item.output ?? {}}/></div></section>{item.deadLetters?.length ? <section><h2>Dead letters</h2><CodeViewer value={item.deadLetters}/></section> : null}</div>}<ConfirmDialog open={cancelOpen} title={locale === "fa" ? "لغو این اجرا؟" : "Cancel this execution?"} body={locale === "fa" ? "پردازش در اولین نقطه امن متوقف می‌شود." : "Processing will stop at the next safe point."} confirmLabel={locale === "fa" ? "لغو اجرا" : "Cancel execution"} pending={pending === "cancel"} onClose={() => setCancelOpen(false)} onConfirm={() => action("cancel")}/></PanelShell>;
}
