spring.data.mongodb.uri=mongodb://localhost:27017/bot_adapter_service
ai-orchestrator.base-url=http://localhost:9121
ai-orchestrator.public-base-url=http://localhost:8001
ai-orchestrator.telegram-base-url=https://api.telegram.org
ai-orchestrator.bale-base-url=https://tapi.bale.ai
ai-orchestrator.bot-secret-env-prefix=CYAN_BOT_SECRET_
