server.port=9126
spring.application.name=bot-adapter-service
eureka.client.serviceUrl.defaultZone=http://admin:CyanAdmin@localhost:8761/eureka
spring.data.mongodb.uri=mongodb://localhost:27017/bot_adapter_service
spring.data.mongodb.auto-index-creation=true
ai-orchestrator.base-url=http://localhost:9121
