spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.mongodb.uri=mongodb://localhost:27017/inventory_service

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
