package com.cyancoder.report.service;
import com.cyancoder.dynamiccore.runtime.DynamicRuntimeService;import com.cyancoder.dynamiccore.runtime.DynamicScope;import com.cyancoder.dynamiccore.store.mongo.DynamicEntityRecordDocument;import com.cyancoder.report.entity.ReportRunEntity;import com.cyancoder.report.model.ReportContracts.*;import com.cyancoder.report.model.ReportRunRequest;import com.cyancoder.report.model.ReportRunResponse;import com.cyancoder.report.repository.ReportRunRepository;import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import java.time.Instant;import java.util.*;import org.springframework.data.domain.PageRequest;import org.springframework.data.domain.Sort;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
@Service public class EndpointReportService{private final DynamicRuntimeService runtime;private final DynamicReportQueryService query;private final ReportRunRepository runs;private final TenantMembershipClient memberships;private final ObjectMapper json;public EndpointReportService(DynamicRuntimeService r,DynamicReportQueryService q,ReportRunRepository rr,TenantMembershipClient m,ObjectMapper j){runtime=r;query=q;runs=rr;memberships=m;json=j;}
 public ReportPage list(String tenant,String site,String actor,String q,int page,int size){scope(tenant,actor);List<DynamicEntityRecordDocument> all;try{all=runtime.listRecords("dynamic-report",new DynamicScope(tenant,site));}catch(Exception e){all=List.of();}String needle=q==null?"":q.trim().toLowerCase();List<ReportSummary> items=all.stream().map(this::summary).filter(x->needle.isBlank()||(x.reportKey()+" "+x.title()).toLowerCase().contains(needle)).toList();int safe=Math.max(1,Math.min(size,100)),from=Math.min(Math.max(0,page)*safe,items.size()),to=Math.min(from+safe,items.size());return new ReportPage(items.subList(from,to),Math.max(0,page),safe,items.size());}
 public ReportSummary get(String tenant,String site,String actor,String key){scope(tenant,actor);return summary(runtime.getRecord("dynamic-report",key,new DynamicScope(tenant,site)));}
 public ReportSummary save(String tenant,String site,String actor,String path,SaveReportRequest in){scope(tenant,actor);String key=required(path==null?in.reportKey():path,"reportKey");ensureDefinition(tenant,site);Map<String,Object>d=new LinkedHashMap<>();d.put("reportKey",key);d.put("title",required(in.title(),"title"));d.put("sourceType","DYNAMIC");d.put("serviceKey",required(in.serviceKey(),"serviceKey"));d.put("entityKey",required(in.entityKey(),"entityKey"));d.put("defaultFilterField",n(in.defaultFilterField()));d.put("defaultSumField",n(in.defaultSumField()));d.put("groupByField",n(in.groupByField()));d.put("filters",in.filters()==null?List.of():in.filters());return summary(runtime.submitMap("dynamic-report",key,d,true,new DynamicScope(tenant,site)));}
 @Transactional public ReportRunView run(String tenant,String site,String actor,String key,String idem,ReportRunRequest req){scope(tenant,actor);if(idem==null||idem.isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Idempotency-Key is required");return runs.findByTenantKeyAndIdempotencyKey(tenant,idem).map(this::view).orElseGet(()->execute(tenant,site,actor,key,idem,req));}
 private ReportRunView execute(String tenant,String site,String actor,String key,String idem,ReportRunRequest req){get(tenant,site,actor,key);ReportRunEntity e=new ReportRunEntity();e.setRunId(UUID.randomUUID().toString());e.setTenantKey(tenant);e.setSiteKey(site);e.setReportKey(key);e.setActor(actor);e.setIdempotencyKey(idem);e.setStatus("RUNNING");e.setCreatedAt(Instant.now());e.setStartedAt(Instant.now());e.setRequestJson(write(req));runs.save(e);try{ReportRunResponse result=query.run("dynamic-report",key,req,new DynamicScope(tenant,site));e.setResultJson(write(result));e.setStatus("SUCCEEDED");}catch(Exception ex){e.setStatus("FAILED");e.setErrorCode("REPORT_RUN_FAILED");e.setErrorMessage(safe(ex.getMessage()));}e.setCompletedAt(Instant.now());return view(runs.save(e));}
 public ReportRunPage history(String tenant,String site,String actor,String key,int page,int size){scope(tenant,actor);var p=runs.findByTenantKeyAndSiteKeyAndReportKey(tenant,site,key,PageRequest.of(Math.max(0,page),Math.max(1,Math.min(100,size)),Sort.by(Sort.Direction.DESC,"createdAt")));return new ReportRunPage(p.getContent().stream().map(this::view).toList(),p.getNumber(),p.getSize(),p.getTotalElements());}
 public ReportRunView runView(String tenant,String site,String actor,String key,String id){scope(tenant,actor);ReportRunEntity e=runs.findByRunIdAndTenantKeyAndSiteKey(id,tenant,site).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Report run not found"));if(!e.getReportKey().equals(key))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Report run not found");return view(e);}
 private void ensureDefinition(String t,String s){try{runtime.getDefinition("dynamic-report",new DynamicScope(t,s));}catch(Exception e){runtime.createFromTemplate("dynamic-report","dynamic-report",new DynamicScope(t,s));}}
 private void scope(String t,String a){memberships.requireMembership(t,a);} private ReportSummary summary(DynamicEntityRecordDocument r){Map<String,Object>d=r.getData()==null?Map.of():r.getData();return new ReportSummary(r.getRecordKey(),Objects.toString(d.get("title"),r.getRecordKey()),Objects.toString(d.get("serviceKey"),""),Objects.toString(d.get("entityKey"),""),Objects.toString(d.get("defaultSumField"),""),Objects.toString(d.get("groupByField"),""),r.getUpdatedAt());}
 private ReportRunView view(ReportRunEntity e){Map<String,Object> req=read(e.getRequestJson(),new TypeReference<>(){});ReportRunResponse result=read(e.getResultJson(),new TypeReference<>(){});return new ReportRunView(e.getRunId(),e.getReportKey(),e.getStatus(),req,result,e.getErrorCode(),e.getErrorMessage(),e.getCreatedAt(),e.getStartedAt(),e.getCompletedAt());}private String write(Object v){try{return v==null?null:json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("Payload could not be serialized",e);}}private <T>T read(String v,TypeReference<T> t){try{return v==null?null:json.readValue(v,t);}catch(Exception e){return null;}}private String required(String v,String f){if(v==null||v.isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,f+" is required");return v.trim();}private String n(String v){return v==null?"":v.trim();}private String safe(String v){return v==null?"Report run failed":v.substring(0,Math.min(v.length(),1000));}}
