import {expect,test,type Page,type Route} from "@playwright/test";
const bootstrap={identity:{username:"admin@cyan.local",email:"admin@cyan.local",mfaEnabled:false,roles:["user"],active:true},access:{realmRoles:["tenant-admin"],realmPermissions:["panel:read","project.create","project.read","definition.read","record.read","bpm.read","automation.read","settings.read"],clients:[{clientId:"cyan-panel",clientRoles:["builder"],clientPermissions:[]}]},tenants:[{tenantKey:"acme",displayName:"Acme",status:"ACTIVE",membershipRole:"TENANT_OWNER"}],sites:[{tenantKey:"acme",siteKey:"main",name:"Main",status:"ACTIVE"}],activeTenantKey:"acme",activeSiteKey:"main",subscription:{tenantKey:"acme",planKey:"growth",status:"ACTIVE",features:[],limits:{},providerState:"CONFIGURED"},capabilities:["ai-orchestrator","dynamic-entities","bpm","automation"].map(key=>({key,enabled:true,source:"PLAN",status:"AVAILABLE",limits:{}})),featureFlags:{},services:{identity:"AVAILABLE",tenancy:"AVAILABLE",sessionScope:"AVAILABLE",sites:"AVAILABLE",billing:"AVAILABLE",capabilities:"AVAILABLE"},warnings:[]};
const flow={flowKey:"customer-enrichment",version:1,name:"Customer enrichment",active:false,entryNodeId:"manual",runtimeMode:"VARIABLES",nodes:[{id:"manual",type:"MANUAL_TRIGGER",name:"Manual",enabled:true,config:{},position:{x:100,y:120}},{id:"ai",type:"AI_OPERATION",name:"Enrich content",enabled:true,config:{operation:"TRANSFORM_DATA",instructions:"Normalize customer data",input:"${variables}",resultPath:"aiResult"},position:{x:360,y:120}}],edges:[{id:"e1",fromNodeId:"manual",toNodeId:"ai"}],inputsSchema:{},outputsSchema:{},labels:[],environment:"default",lifecycleStatus:"DRAFT",requiredRoles:[],settings:{},pinData:{}};
const bpm={flowKey:"customer-review",version:1,name:"Customer review",description:"",startState:"review",states:[{id:"review",displayName:"Review",terminal:false,candidateGroups:[],onEnterActions:[],submitMode:"DYNAMIC",entityService:"crm-service",entityKey:"crm-lead"},{id:"done",displayName:"Done",terminal:true,candidateGroups:[],onEnterActions:[],submitMode:"DYNAMIC"}],transitions:[{id:"approve",fromState:"review",toState:"done",label:"Approve",allowedGroups:[],allowedRoles:[],conditions:[]}],layout:{review:{x:100,y:120},done:{x:380,y:120}},active:true,lifecycleStatus:"ACTIVE"};
const work={id:"work-1",objectType:"CRM review",flowKey:"customer-review",state:"review",assignee:"admin@cyan.local",priority:"HIGH",locked:false,payload:{currentFormValues:{name:"Customer"}},auditLog:[],transitionHistory:[],automationBlockRegistry:[],updatedAt:"2026-08-06T10:00:00Z"};
async function prepare(page:Page){await page.addInitScript(()=>{localStorage.setItem("cyan.panel.authToken","token");localStorage.setItem("cyan.panel.authExpiresAt",String(Date.now()+3600000));localStorage.setItem("cyan.panel.sessionId","session");localStorage.setItem("cyan.panel.username","admin@cyan.local")});await page.route("**/api/panel/bootstrap",r=>r.fulfill({json:bootstrap}));await page.route("**/api/platform/**",platform)}
async function platform(route:Route){const url=route.request().url(),method=route.request().method();if(url.includes("node-structures"))return route.fulfill({json:[{type:"MANUAL_TRIGGER",commonFields:[],configFields:[],category:"TRIGGERS"},{type:"AI_OPERATION",commonFields:[],configFields:["operation","instructions","input","resultPath"],category:"AI"},{type:"END",commonFields:[],configFields:[],category:"DATA_FLOW"}]});if(url.includes("credentials"))return route.fulfill({json:[]});if(url.includes("automation-flows")&&method==="POST")return route.fulfill({json:{...flow,...route.request().postDataJSON()}});if(url.includes("automation-flows/customer-enrichment"))return route.fulfill({json:flow});if(url.includes("automation-flows"))return route.fulfill({json:[flow]});if(url.includes("automation-orchestrator/executions"))return route.fulfill({json:[]});if(url.includes("bpm/metadata/state-actions"))return route.fulfill({json:[{type:"ADD_AUDIT_ENTRY",description:"Audit"},{type:"RUN_AUTOMATION_BLOCK",description:"Run automation"}]});if(url.includes("bpm/metadata/transition-conditions"))return route.fulfill({json:{operators:[],logicalOperators:["AND","OR"],supportedFields:[]}});if(url.includes("bpm/flows")&&method==="POST")return route.fulfill({json:{...bpm,...route.request().postDataJSON(),version:1}});if(url.includes("bpm/flows/customer-review"))return route.fulfill({json:bpm});if(url.includes("bpm/flows"))return route.fulfill({json:[bpm]});if(url.includes("assigned-to-me")||url.includes("visible-to-me"))return route.fulfill({json:[work]});if(url.includes("work-1/active-form"))return route.fulfill({json:{objectId:"work-1",objectType:"CRM review",flowKey:"customer-review",state:"review",formKey:"crm-lead",rendererDefinition:{fields:{name:{type:"string",required:true,label:"Name"}}},entityService:"crm-service",entityKey:"crm-lead",submitMode:"DYNAMIC"}});if(url.includes("work-1/transitions"))return route.fulfill({json:[{transitionId:"approve",label:"Approve",fromState:"review",toState:"done"}]});if(url.includes("work-1/comments")||url.includes("work-1/attachments"))return route.fulfill({json:[]});if(url.includes("work-1"))return route.fulfill({json:work});return route.fulfill({json:[]})}
test("automation AI node saves once while the button is pending",async({page})=>{await prepare(page);let saves=0;await page.route("**/endpoint/automation-flows",async route=>{if(route.request().method()==="POST"){saves++;await new Promise(r=>setTimeout(r,1200));return route.fulfill({json:{...flow,...route.request().postDataJSON()}})}return platform(route)});await page.goto("/automations/new");await page.getByLabel("Flow key").fill("customer-enrichment");await page.getByLabel("Name").fill("Customer enrichment");await page.getByText("AI operation",{exact:true}).click();await page.getByLabel("Instructions").fill("Normalize customer data");const save=page.getByRole("button",{name:"Save"});await save.click();await expect(page.getByRole("button",{name:"Saving…"})).toBeDisabled();await page.waitForTimeout(100);await expect.poll(()=>saves).toBe(1)});
test("BPM and work routes expose editable and operational actions",async({page})=>{await prepare(page);await page.route("**/managed-objects/cartable**",route=>route.fulfill({json:{content:[work],totalElements:1,page:0,size:20}}));await page.goto("/bpm/customer-review");await expect(page.getByText("Review",{exact:true}).first()).toBeVisible();await page.goto("/work");await page.getByRole("link",{name:/CRM review/}).click();await page.waitForURL("**/work/work-1");await expect(page.getByRole("heading",{name:"crm-lead"})).toBeVisible();await expect(page.getByRole("button",{name:"Approve"})).toBeEnabled();await expect(page.getByLabel("Name")).toHaveValue("Customer")});
test("persisted automation and BPM graph nodes render",async({page})=>{
  await prepare(page);
  await page.goto("/automations/customer-enrichment");
  await expect(page.locator(".react-flow__node")).toHaveCount(2);
  await expect(page.locator(".react-flow__node").first()).toBeVisible();
  await page.goto("/bpm/customer-review");
  await expect(page.locator(".react-flow__node")).toHaveCount(2);
  await expect(page.locator(".react-flow__node").first()).toBeVisible();
});
test("captures Phase 6 and 7 responsive theme and RTL states",async({page})=>{test.setTimeout(180000);test.skip(process.env.CAPTURE_PHASES_6_7!=="1","Visual capture is explicit");await prepare(page);await page.goto("/");for(const target of [{phase:6,path:"/automations/customer-enrichment",ready:".automation-editor-grid"},{phase:7,path:"/bpm/customer-review",ready:".bpm-designer-grid"},{phase:7,path:"/work/work-1",ready:".work-item-layout"}])for(const state of [{name:"desktop-en-light",w:1440,h:1000,l:"en",t:"light"},{name:"desktop-en-dark",w:1440,h:1000,l:"en",t:"dark"},{name:"tablet-en-light",w:834,h:1112,l:"en",t:"light"},{name:"mobile-en-light",w:390,h:844,l:"en",t:"light"},{name:"mobile-en-dark",w:390,h:844,l:"en",t:"dark"},{name:"desktop-fa-rtl-light",w:1440,h:1000,l:"fa",t:"light"},{name:"mobile-fa-rtl-light",w:390,h:844,l:"fa",t:"light"}]){await page.setViewportSize({width:state.w,height:state.h});await page.evaluate(({l,t})=>{localStorage.setItem("cyan.panel.locale",l);localStorage.setItem("cyan.panel.theme",t)},{l:state.l,t:state.t});await page.goto(target.path);await expect(page.locator(target.ready)).toBeVisible();await page.screenshot({path:`../docs/ui-redesign/completion/phase-${target.phase}/screenshots/${target.path.includes("work/")?"work-":""}${state.name}.png`})}});
