import {expect,test,type Page,type Route} from "@playwright/test";

const permissions=["*","team.read","team.manage","roles.manage","settings.read","settings.manage","billing.read","billing.manage"];
const bootstrap={identity:{username:"platform-admin",email:"admin@example.test",phoneNumber:"+10000000000",mfaEnabled:true,roles:["admin"],active:true},access:{realmRoles:["platform-admin"],realmPermissions:["realm:manage","*"],clients:[]},tenantAccess:{tenantKey:"north-star",username:"platform-admin",roleKey:"TENANT_OWNER",permissions:["*"],active:true},tenants:[{tenantKey:"north-star",displayName:"North Star",status:"ACTIVE",membershipRole:"TENANT_OWNER"}],sites:[],activeTenantKey:"north-star",activeSiteKey:null,subscription:{tenantKey:"north-star",planKey:"starter",status:"ACTIVE",features:["bpm","automation"],limits:{},providerState:"NOT_REQUIRED"},capabilities:["bpm","automation","dynamic-entities","site-builder"].map(key=>({key,enabled:true,source:"PLAN",status:"AVAILABLE",limits:{}})),featureFlags:{},services:{identity:"AVAILABLE",tenancy:"AVAILABLE",sessionScope:"AVAILABLE",billing:"AVAILABLE",capabilities:"AVAILABLE"},warnings:[]};
const roles=[{roleKey:"TENANT_OWNER",displayName:"Owner",description:"Platform-managed tenant role",systemRole:true,revision:0,permissions:["*"],memberCount:1},{roleKey:"TENANT_MEMBER",displayName:"Member",description:"Day-to-day access",systemRole:true,revision:0,permissions:["record.read","bpm.read"],memberCount:1}];
const users=[{username:"platform-admin",email:"admin@example.test",roleKey:"TENANT_OWNER",active:true,joinedAt:"2026-08-01T10:00:00Z",updatedAt:"2026-08-01T10:00:00Z"},{username:"operator",email:"operator@example.test",roleKey:"TENANT_MEMBER",active:true,joinedAt:"2026-08-02T10:00:00Z",updatedAt:"2026-08-02T10:00:00Z"}];
const catalog=permissions.filter(key=>key!=="*").map(key=>({key,groupKey:key.startsWith("billing")?"Billing":key.startsWith("settings")?"Workspace":"Team",displayName:key,description:`Permission ${key}`}));
async function prepare(page:Page){await page.addInitScript(()=>{localStorage.setItem("cyan.panel.authToken","test-token");localStorage.setItem("cyan.panel.authExpiresAt",String(Date.now()+3600000));localStorage.setItem("cyan.panel.sessionId","session-8");localStorage.setItem("cyan.panel.username","platform-admin")});await page.route("**/api/panel/bootstrap",route=>route.fulfill({json:bootstrap}));await page.route("**/api/sso/sessions/me**",route=>route.fulfill({json:[{sessionId:"session-8",clientId:"cyan-panel",deviceId:"Browser",active:true,issuedAtEpochSecond:1786176000,expiresAtEpochSecond:1786262400}]}));await page.route("**/api/platform/**",platform)}
async function platform(route:Route){const url=route.request().url();if(url.includes("permissions/catalog"))return route.fulfill({json:catalog});if(url.includes("/roles"))return route.fulfill({json:route.request().method()==="POST"?{roleKey:"OPERATIONS",displayName:"Operations",systemRole:false,revision:0,permissions:["team.read"],memberCount:0}:roles});if(url.includes("/users"))return route.fulfill({json:route.request().method()==="POST"?{...route.request().postDataJSON(),active:true,joinedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}:users});if(url.includes("/endpoint/clients/capabilities"))return route.fulfill({json:["bpm","automation","dynamic-entities","site-builder"]});if(url.endsWith("/endpoint/clients"))return route.fulfill({json:route.request().method()==="POST"?{status:"ACTIVE"}:[{tenantKey:"north-star",displayName:"North Star",status:"ACTIVE",createdAt:"2026-08-01T10:00:00Z"}]});if(url.includes("/billing/plans"))return route.fulfill({json:[{planKey:"starter",displayName:"Starter",description:"Core workspace",billingMode:"FREE",active:true,features:["bpm","automation"],limits:{}}]});return route.fulfill({json:{}})}

test("tenant owner creates a user once while submit is pending",async({page})=>{await prepare(page);let creates=0;await page.route("**/endpoint/tenants/north-star/users",async route=>{if(route.request().method()==="POST"){creates++;await new Promise(resolve=>setTimeout(resolve,800));return route.fulfill({json:{...route.request().postDataJSON(),active:true,joinedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}})}return route.fulfill({json:users})});await page.goto("/team/users");await page.getByRole("button",{name:/Add user/}).click();const dialog=page.getByRole("dialog",{name:"Add user"});await dialog.getByLabel("Username").fill("new-operator");await dialog.getByLabel("Email").fill("new@example.test");await dialog.getByLabel("Initial password").fill("secure-pass-123");const submit=dialog.getByRole("button",{name:"Create user"});await submit.click();await expect(dialog.getByRole("button",{name:"Working…"})).toBeDisabled();await expect.poll(()=>creates).toBe(1)});

test("role, billing, settings, profile and client flows are clickable",async({page})=>{await prepare(page);await page.goto("/team/roles");await expect(page.getByRole("heading",{name:"Owner"})).toBeVisible();await page.getByRole("button",{name:/New role/}).click();await page.getByLabel("Role name").fill("Operations");await page.getByLabel("Role key").fill("OPERATIONS");await page.getByText("Permission team.read").click();await expect(page.getByRole("button",{name:"Save role"})).toBeEnabled();await page.goto("/billing");await expect(page.getByRole("heading",{name:"Starter",level:3,exact:true})).toBeVisible();await page.goto("/settings");await expect(page.getByText("Capabilities & operational state")).toBeVisible();await page.goto("/profile");await expect(page.getByLabel("Email")).toHaveValue("admin@example.test");await page.goto("/clients");await page.getByRole("button",{name:/New client/}).click();await page.getByLabel("Business name").fill("Example Client");await expect(page.getByLabel("Client key")).toHaveValue("example-client")});

test("captures Phase 8 desktop, tablet, mobile, dark and RTL states",async({page})=>{test.setTimeout(180000);test.skip(process.env.CAPTURE_PHASE_8!=="1","Visual capture is explicit");await prepare(page);await page.goto("/dashboard");for(const target of [{name:"team-users",path:"/team/users",ready:".access-table"},{name:"team-roles",path:"/team/roles",ready:".role-layout"},{name:"clients",path:"/clients",ready:".client-grid"},{name:"profile",path:"/profile",ready:".settings-layout"},{name:"billing",path:"/billing",ready:".billing-layout"},{name:"settings",path:"/settings",ready:".settings-stack"}])for(const state of [{name:"desktop-en-light",w:1440,h:1000,l:"en",t:"light"},{name:"desktop-en-dark",w:1440,h:1000,l:"en",t:"dark"},{name:"tablet-en-light",w:834,h:1112,l:"en",t:"light"},{name:"mobile-en-light",w:390,h:844,l:"en",t:"light"},{name:"desktop-fa-rtl-light",w:1440,h:1000,l:"fa",t:"light"},{name:"mobile-fa-rtl-light",w:390,h:844,l:"fa",t:"light"}]){await page.setViewportSize({width:state.w,height:state.h});await page.evaluate(({l,t})=>{localStorage.setItem("cyan.panel.locale",l);localStorage.setItem("cyan.panel.theme",t)},{l:state.l,t:state.t});await page.goto(target.path);await expect(page.locator(target.ready)).toBeVisible();await page.screenshot({path:`../docs/ui-redesign/completion/phase-8/screenshots/${target.name}-${state.name}.png`,fullPage:true})}});
