import { expect, test, type Page, type Route } from "@playwright/test";
const scope={tenantKey:"test-tenant",siteKey:"main-site"};
const bootstrap={identity:{username:"operator",roles:["admin"],active:true,mfaEnabled:false},access:{realmRoles:["admin"],realmPermissions:["*"],clients:[]},tenantAccess:{...scope,username:"operator",roleKey:"TENANT_OWNER",permissions:["*"],active:true},tenants:[{tenantKey:scope.tenantKey,displayName:"Test workspace",status:"ACTIVE",membershipRole:"TENANT_OWNER"}],sites:[{...scope,name:"Main site",status:"ACTIVE"}],activeTenantKey:scope.tenantKey,activeSiteKey:scope.siteKey,subscription:{tenantKey:scope.tenantKey,planKey:"test",status:"ACTIVE",features:[],limits:{},providerState:"NOT_REQUIRED"},capabilities:["report","media","search"].map(key=>({key,enabled:true,source:"PLAN",status:"AVAILABLE",limits:{}})),featureFlags:{},services:{"report-service":"AVAILABLE","media-service":"AVAILABLE","search-index-service":"AVAILABLE"},warnings:[]};
const report={reportKey:"operations",title:"Operations report",serviceKey:"crm-service",entityKey:"customer",defaultSumField:"",groupByField:"",updatedAt:"2026-08-09T08:00:00Z"};const index={indexKey:"content",sourceServiceKey:"content-service",sourceEntityKey:"article",sourceEntityType:"CONTENT",engine:"MONGO_PROJECTION",status:"ACTIVE",searchableFields:[{fieldPath:"title",analyzer:"standard",boost:2}],facetFields:[],sortableFields:[],filterableFields:[],suggestFields:[],updatedAt:"2026-08-09T08:00:00Z"};const asset={assetKey:"asset-1",originalFileName:"guide.pdf",mimeType:"application/pdf",assetType:"DOCUMENT",visibility:"PRIVATE",sizeBytes:2048,status:"UPLOADED",createdAt:"2026-08-09T08:00:00Z",metadata:{seo:{title:"Guide"}}};
async function prepare(page:Page){await page.addInitScript(()=>{localStorage.setItem("cyan.panel.authToken","test-token");localStorage.setItem("cyan.panel.authExpiresAt",String(Date.now()+3600000));localStorage.setItem("cyan.panel.sessionId","phase-10")});await page.route("**/api/panel/bootstrap",route=>route.fulfill({json:bootstrap}));await page.route("**/api/platform/**",platform);await page.goto("/dashboard")}
async function platform(route:Route){
  const url=route.request().url(),method=route.request().method();
  if(url.includes("/endpoint/platform-health/runs")){const value={runId:"health-1",status:"HEALTHY",checks:[{serviceKey:"report-service",status:"AVAILABLE",detail:"Service route is registered",durationMs:1}],createdAt:new Date().toISOString(),completedAt:new Date().toISOString()};return route.fulfill({json:method==="POST"?value:{items:[value],page:0,size:20,total:1}})}
  if(url.includes("/endpoint/reports")){if(url.includes("/exports"))return route.fulfill({json:[]});if(url.includes("/runs")){if(method==="POST")return route.fulfill({json:{runId:"run-1",reportKey:report.reportKey,status:"SUCCEEDED",result:{reportKey:report.reportKey,count:1,sum:0,groups:{},rows:[{recordKey:"record-1",title:"Result"}]},createdAt:new Date().toISOString()}});return route.fulfill({json:{items:[],page:0,size:20,total:0}})}if(/\/reports\/[^?]+/.test(url))return route.fulfill({json:report});return route.fulfill({json:{items:[report],page:0,size:20,total:1}})}
  if(url.includes("/endpoint/media/assets")){if(url.includes("/usage"))return route.fulfill({json:{assetKey:"asset-1",status:"UNREFERENCED",referenceCount:0,references:[]}});return route.fulfill({json:{items:[asset],page:0,size:24,total:1}})}
  if(url.includes("/endpoint/search-index/definitions"))return route.fulfill({json:method==="GET"?[index]:index});
  if(url.includes("/endpoint/search-index/stats"))return route.fulfill({json:{indexKey:index.indexKey,documentCount:1,health:"AVAILABLE",lastRun:{runId:"sync-1",indexKey:index.indexKey,status:"SUCCEEDED",scannedCount:1,syncedCount:1,failedCount:0,createdAt:new Date().toISOString()}}});
  if(url.includes("/endpoint/search-index/sync"))return route.fulfill({json:{runId:"sync-2",indexKey:index.indexKey,status:"SUCCEEDED",scannedCount:1,syncedCount:1,failedCount:0,createdAt:new Date().toISOString()}});
  if(url.includes("/endpoint/search-index/search"))return route.fulfill({json:{query:"result",page:0,size:20,total:1,items:[{documentKey:"doc-1",title:"Result document",summary:"Structured response",entityType:"CONTENT",source:{recordKey:"record-1"}}],facetCounts:{}}});
  if(url.includes("/endpoint/search-index/suggest"))return route.fulfill({json:{query:"result",suggestions:["Result document"]}});
  return route.fulfill({json:[]});
}
test.beforeEach(async({page})=>prepare(page));
test("Phase 10 routes render structured service data",async({page})=>{test.setTimeout(90000);await page.goto("/reports");await expect(page.getByText("Operations report",{exact:true})).toBeVisible();await page.getByRole("link",{name:/Operations report/}).click();await expect(page.getByRole("button",{name:"Run report"})).toBeEnabled();await page.goto("/media");await page.getByRole("button",{name:/guide.pdf/}).click();await expect(page.getByRole("button",{name:"Delete asset"})).toBeEnabled();await page.goto("/search");await expect(page.getByRole("heading",{name:"content"})).toBeVisible();await page.getByRole("tab",{name:"Query tester"}).click();await page.getByLabel("Search query").fill("result");await page.getByRole("button",{name:"Run query"}).click();await expect(page.locator(".search-result-list article").getByText("Result document")).toBeVisible();await page.goto("/platform/health");await expect(page.getByRole("button",{name:"Run checks"})).toBeEnabled();await page.goto("/platform/roadmap");await expect(page).toHaveURL(/\/platform\/health$/)});
test("report run disables duplicate submission while pending",async({page})=>{let calls=0;await page.route("**/endpoint/reports/operations/runs",async route=>{if(route.request().method()==="POST"){calls++;await new Promise(resolve=>setTimeout(resolve,650));return route.fulfill({json:{runId:"run-1",reportKey:"operations",status:"SUCCEEDED",result:{reportKey:"operations",count:0,sum:0,groups:{},rows:[]},createdAt:new Date().toISOString()}})}return route.fulfill({json:{items:[],page:0,size:20,total:0}})});await page.goto("/reports/operations");const button=page.getByRole("button",{name:"Run report"});await button.click();await expect(page.getByRole("button",{name:"Running…"})).toBeDisabled();await expect.poll(()=>calls).toBe(1)});
test("capture Phase 10 responsive theme and RTL states",async({page})=>{test.setTimeout(240000);test.skip(process.env.CAPTURE_PHASE_10!=="1","Visual capture is explicit");const targets=[{name:"reports",path:"/reports",ready:".operational-list"},{name:"report-detail",path:"/reports/operations",ready:".report-workspace"},{name:"media",path:"/media",ready:".media-layout"},{name:"search",path:"/search",ready:".search-workspace"},{name:"health",path:"/platform/health",ready:".health-grid"}];const states=[{name:"desktop-en-light",w:1440,h:1000,l:"en",t:"light"},{name:"desktop-en-dark",w:1440,h:1000,l:"en",t:"dark"},{name:"tablet-en-light",w:834,h:1112,l:"en",t:"light"},{name:"mobile-en-light",w:390,h:844,l:"en",t:"light"},{name:"desktop-fa-rtl-light",w:1440,h:1000,l:"fa",t:"light"},{name:"mobile-fa-rtl-dark",w:390,h:844,l:"fa",t:"dark"}];for(const target of targets)for(const state of states){await page.setViewportSize({width:state.w,height:state.h});await page.evaluate(({l,t})=>{localStorage.setItem("cyan.panel.locale",l);localStorage.setItem("cyan.panel.theme",t)},{l:state.l,t:state.t});await page.goto(target.path);await expect(page.locator(target.ready).first()).toBeVisible();await page.screenshot({path:`../docs/ui-redesign/completion/phase-10/screenshots/${target.name}-${state.name}.png`,fullPage:true})}});
