import { expect, test, type Page, type Route } from "@playwright/test";

const tenantKey = "contract-tenant", siteKey = "main-site";
const bootstrap = { identity:{username:"owner",email:"owner@example.test",roles:["admin"],active:true,mfaEnabled:true},access:{realmRoles:["admin"],realmPermissions:["*"],clients:[]},tenantAccess:{tenantKey,siteKey,username:"owner",roleKey:"TENANT_OWNER",permissions:["*"],active:true},tenants:[{tenantKey,displayName:"Contract tenant",status:"ACTIVE",membershipRole:"TENANT_OWNER"}],sites:[{tenantKey,siteKey,name:"Main site",status:"ACTIVE"}],activeTenantKey:tenantKey,activeSiteKey:siteKey,subscription:{tenantKey,planKey:"test",status:"ACTIVE",features:[],limits:{},providerState:"NOT_REQUIRED"},capabilities:["ai-orchestrator","bpm","site-builder","report","media"].map(key=>({key,enabled:true,source:"TENANT_OVERRIDE",status:"AVAILABLE",limits:{}})),featureFlags:{},services:{identity:"AVAILABLE",tenancy:"AVAILABLE",sessionScope:"AVAILABLE"},warnings:[] };
const item={id:"work-1",objectType:"case",flowKey:"review",state:"OPEN",assignee:"owner",assigneeType:"USER",payload:{},priority:"HIGH",updatedAt:"2026-08-09T10:00:00Z"};
const report={reportKey:"operations",title:"Operations",serviceKey:"crm-service",entityKey:"customer",defaultSumField:"",groupByField:""};
const run={runId:"run-1",reportKey:"operations",status:"SUCCEEDED",result:{reportKey:"operations",count:1,sum:0,groups:{},rows:[{recordKey:"record-1"}]},createdAt:"2026-08-09T10:00:00Z"};
const asset={assetKey:"asset-1",originalFileName:"guide.pdf",mimeType:"application/pdf",assetType:"DOCUMENT",visibility:"PRIVATE",sizeBytes:2048,status:"UPLOADED",createdAt:"2026-08-09T10:00:00Z",metadata:{}};
let reportExports: Array<Record<string, unknown>> = [];

async function prepare(page:Page){await page.addInitScript(()=>{localStorage.setItem("cyan.panel.authToken","contract-token");localStorage.setItem("cyan.panel.authExpiresAt",String(Date.now()+3600000));localStorage.setItem("cyan.panel.sessionId","contract-session");localStorage.setItem("cyan.panel.username","owner")});await page.route("**/api/panel/bootstrap",route=>route.fulfill({json:bootstrap}));await page.route("**/api/sso/sessions/me",route=>route.fulfill({json:[]}));await page.route("**/api/platform/**",platform)}
async function platform(route:Route){const url=route.request().url(),method=route.request().method();
  if(url.includes("provider-profiles"))return route.fulfill({json:method==="PUT"?{...route.request().postDataJSON(),configurationStatus:"NOT_CONFIGURED",revision:1,updatedAt:new Date().toISOString()}:[]});
  if(url.includes("artifact-jobs"))return route.fulfill({json:method==="POST"?{jobId:"job-1",status:"QUEUED",...route.request().postDataJSON(),createdAt:new Date().toISOString()}:[]});
  if(url.includes("managed-objects/cartable"))return route.fulfill({json:{content:[item],totalElements:1,page:0,size:20}});
  if(url.includes(`/sites/${siteKey}/portal/work`))return route.fulfill({json:{content:[item],totalElements:1,page:0,size:20}});
  if(url.includes("/permissions/catalog"))return route.fulfill({json:[{key:"team.manage",groupKey:"Team",displayName:"Manage team",description:"Manage team"}]});
  if(url.includes("/roles"))return route.fulfill({json:[{roleKey:"TENANT_OWNER",displayName:"Owner",systemRole:true,revision:0,permissions:["*"],memberCount:1},{roleKey:"TENANT_MEMBER",displayName:"Member",systemRole:true,revision:0,permissions:["team.read"],memberCount:1}]});
  if(url.includes("/users"))return route.fulfill({json:[{username:"owner",email:"owner@example.test",roleKey:"TENANT_OWNER",active:true,joinedAt:"2026-08-09T10:00:00Z",updatedAt:"2026-08-09T10:00:00Z"},{username:"member",email:"member@example.test",roleKey:"TENANT_MEMBER",active:true,joinedAt:"2026-08-09T10:00:00Z",updatedAt:"2026-08-09T10:00:00Z"}]});
  if(url.includes("/invitations"))return route.fulfill({json:method==="POST"?{invitationId:"invite-1",tenantKey,email:"new@example.test",roleKey:"TENANT_MEMBER",status:"PENDING",deliveryStatus:"NOT_CONFIGURED",expiresAt:"2026-08-12T10:00:00Z",createdAt:new Date().toISOString()}:[]});
  if(url.includes("ownership/transfer"))return route.fulfill({json:{username:"member",roleKey:"TENANT_OWNER",active:true}});
  if(url.includes("/endpoint/clients/capabilities/catalog"))return route.fulfill({json:["bpm","automation"]});
  if(url.includes(`/endpoint/tenants/${tenantKey}/capabilities`))return route.fulfill({json:[{key:"bpm",enabled:true,source:"TENANT_OVERRIDE",status:"AVAILABLE"}]});
  if(url.includes("/endpoint/clients"))return route.fulfill({json:[{tenantKey,displayName:"Contract tenant",status:"ACTIVE",createdAt:"2026-08-09T10:00:00Z"}]});
  if(url.includes("/billing/plans"))return route.fulfill({json:[{planKey:"free",displayName:"Free",billingMode:"FREE",active:true}]});
  if(url.includes("/endpoint/reports/operations/runs/run-1/exports")){if(method==="POST"){const value={exportId:"export-1",reportKey:"operations",runId:"run-1",format:route.request().postDataJSON().format,status:"SUCCEEDED",assetKey:"export-asset",createdAt:new Date().toISOString()};reportExports=[value];return route.fulfill({json:value})}return route.fulfill({json:reportExports})}
  if(url.includes("/endpoint/reports/operations/runs"))return route.fulfill({json:method==="POST"?run:{items:[run],page:0,size:20,total:1}});
  if(url.includes("/endpoint/reports/operations"))return route.fulfill({json:report});
  if(url.includes("/endpoint/media/assets/asset-1/usage"))return route.fulfill({json:{assetKey:"asset-1",status:"UNREFERENCED",referenceCount:0,references:[]}});
  if(url.includes("/endpoint/media/assets/asset-1")&&method==="DELETE")return route.fulfill({status:204});
  if(url.includes("/endpoint/media/assets"))return route.fulfill({json:{items:[asset],page:0,size:24,total:1}});
  if(url.includes("/endpoint/platform-health/runs")){const health={runId:"health-1",status:"HEALTHY",checks:[{serviceKey:"report-service",status:"AVAILABLE",detail:"Service route is registered",durationMs:1}],createdAt:new Date().toISOString(),completedAt:new Date().toISOString()};return route.fulfill({json:method==="POST"?health:{items:[health],page:0,size:20,total:1}})}
  return route.fulfill({json:[]});
}
test.beforeEach(async({page})=>{reportExports=[];await prepare(page)});

test("new Phase 11 operational surfaces use persisted contracts",async({page})=>{await page.goto("/work");await expect(page.getByText("case",{exact:true})).toBeVisible();await page.goto(`/sites/${siteKey}/portal`);await expect(page.getByText("case",{exact:true})).toBeVisible();await page.goto("/ai/providers");await expect(page.getByRole("heading",{name:"Custom API profile"})).toBeVisible();await page.goto("/reports/operations");await expect(page.getByRole("button",{name:"CSV"})).toBeEnabled();await page.getByRole("button",{name:"CSV"}).click();await page.reload();await expect(page.getByText(/CSV · export-asset/)).toBeVisible();await page.goto("/platform/health");await expect(page.getByText("report-service")).toBeVisible()});

test("tenant invitation and ownership controls disable duplicate actions",async({page})=>{let invites=0;await page.route(`**/endpoint/tenants/${tenantKey}/invitations`,async route=>{if(route.request().method()==="POST"){invites++;await new Promise(resolve=>setTimeout(resolve,500));return route.fulfill({json:{invitationId:"invite-1",tenantKey,email:"new@example.test",roleKey:"TENANT_MEMBER",status:"PENDING",deliveryStatus:"NOT_CONFIGURED",expiresAt:"2026-08-12T10:00:00Z",createdAt:new Date().toISOString()}})}return route.fulfill({json:[]})});await page.goto("/team/users");const invitation=page.locator("section").filter({has:page.getByRole("heading",{name:"Invite member"})});await invitation.getByLabel("Email").fill("new@example.test");const send=invitation.getByRole("button",{name:"Send invitation"});await send.click();await expect(invitation.getByRole("button",{name:"Working…"})).toBeDisabled();await expect.poll(()=>invites).toBe(1)});

test("custom AI generation and safe media deletion block repeated mutation",async({page})=>{let profiles=0;await page.route("**/provider-profiles/custom-ai",async route=>{profiles++;await new Promise(resolve=>setTimeout(resolve,500));return route.fulfill({json:{...route.request().postDataJSON(),configurationStatus:"NOT_CONFIGURED",revision:1,updatedAt:new Date().toISOString()}})});await page.goto("/ai/providers");await page.getByLabel("Profile key").fill("custom-ai");await page.getByLabel("Display name").fill("Custom AI");await page.getByLabel("HTTPS base URL").fill("https://ai.example.test");await page.getByLabel("Model").fill("model-1");await page.getByLabel("Secret reference").fill("env:CUSTOM_AI_KEY");await page.getByRole("button",{name:"Save profile"}).click();await expect(page.getByRole("button",{name:"Working…"})).toBeDisabled();await expect.poll(()=>profiles).toBe(1);await page.goto("/media");await page.getByRole("button",{name:/guide.pdf/}).click();await expect(page.getByRole("button",{name:"Delete asset"})).toBeEnabled()});
