plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

ext {
	rndNum = new Random().nextInt(99)
}

group = 'com.cyancoder'
version = "0.0.1.${project.property('rndNum')}-SNAPSHOT"
//version = "0.0.1.${parentNum}-SNAPSHOT"


java {
	sourceCompatibility = '25'
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	compileOnly 'org.projectlombok:lombok:1.18.46'
	annotationProcessor 'org.projectlombok:lombok:1.18.46'
	implementation 'org.axonframework:axon-spring-boot-starter:4.9.0'
}

tasks.named('test') {
	delete "buld/libs/*.jar"

}

// library module shared by other services; it has no main class
bootJar { enabled = false }
jar { enabled = true }
