package com.cyancoder.report.controller;
import com.cyancoder.report.model.ReportContracts.*;import com.cyancoder.report.model.ReportRunRequest;import com.cyancoder.report.service.EndpointReportService;import jakarta.validation.Valid;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/endpoint/reports") public class EndpointReportController{private final EndpointReportService service;public EndpointReportController(EndpointReportService s){service=s;}
 @GetMapping @PreAuthorize("@platformAuthorizationService.canReadService('report-service')") public ReportPage list(@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,Authentication a,@RequestParam(required=false)String q,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return service.list(t,s,a.getName(),q,page,size);}
 @GetMapping("/{key}") @PreAuthorize("@platformAuthorizationService.canReadService('report-service')") public ReportSummary get(@PathVariable String key,@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,Authentication a){return service.get(t,s,a.getName(),key);}
 @PostMapping @PreAuthorize("@platformAuthorizationService.canManageService('report-service')") public ReportSummary create(@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,Authentication a,@RequestBody SaveReportRequest r){return service.save(t,s,a.getName(),null,r);}
 @PutMapping("/{key}") @PreAuthorize("@platformAuthorizationService.canManageService('report-service')") public ReportSummary update(@PathVariable String key,@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,Authentication a,@RequestBody SaveReportRequest r){return service.save(t,s,a.getName(),key,r);}
 @PostMapping("/{key}/runs") @PreAuthorize("@platformAuthorizationService.canManageService('report-service')") public ReportRunView run(@PathVariable String key,@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,@RequestHeader("Idempotency-Key")String i,Authentication a,@RequestBody(required=false)ReportRunRequest r){return service.run(t,s,a.getName(),key,i,r);}
 @GetMapping("/{key}/runs") @PreAuthorize("@platformAuthorizationService.canReadService('report-service')") public ReportRunPage history(@PathVariable String key,@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,Authentication a,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size){return service.history(t,s,a.getName(),key,page,size);}
 @GetMapping("/{key}/runs/{id}") @PreAuthorize("@platformAuthorizationService.canReadService('report-service')") public ReportRunView run(@PathVariable String key,@PathVariable String id,@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,Authentication a){return service.runView(t,s,a.getName(),key,id);}
 @PostMapping("/{key}/runs/{id}/exports") @PreAuthorize("@platformAuthorizationService.canManageService('report-service')") public ReportExportView export(@PathVariable String key,@PathVariable String id,@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,@RequestHeader("Idempotency-Key")String idem,Authentication a,@RequestBody(required=false)CreateReportExportRequest request){return service.export(t,s,a.getName(),key,id,idem,request);}
 @GetMapping("/{key}/runs/{id}/exports") @PreAuthorize("@platformAuthorizationService.canReadService('report-service')") public java.util.List<ReportExportView> exports(@PathVariable String key,@PathVariable String id,@RequestHeader("X-Tenant-Key")String t,@RequestHeader(value="X-Site-Key",required=false)String s,Authentication a){return service.exports(t,s,a.getName(),key,id);}}
