server.port=9125
spring.application.name=search-index-service
eureka.client.serviceUrl.defaultZone=http://admin:CyanAdmin@localhost:8761/eureka
spring.datasource.url=jdbc:postgresql://localhost:5432/search_index_service
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.data.mongodb.uri=mongodb://localhost:27017/search_index_service
spring.data.mongodb.auto-index-creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9001/.well-known/jwks.json
service.internal.username=search_index_internal
service.internal.password=search_index_secret
dynamic.runtime.service-key=search-index-service
dynamic.runtime.check-missing-fields=true
dynamic.runtime.check-extra-fields=true
